### ISSUE TITLE
Direct messaging

### ISSUE THREAD

**Issue by matthijsotterloo** [mgp25/Instagram-API#1290] opened 2017-05-29 14:26 UTC
Not sure if this is on the roadmap, but I see a lot of new features being added.
Is it possible to get a call for direct messaging? (List of direct messages, and a possibility to respond).

Cheers!

**Comment by SteveJobzniak** [comment] 2017-05-29 15:15
@matthijsotterloo Hi, the brilliant @valga has been working hard on implementing all direct messaging functions. You can find them in `dev-master`, in the src/Request/Direct.php file. You access those functions via `$ig->direct->getInbox()` and similar. Have fun!

There's also an open pull request which is getting merged today, which adds two more Direct messaging functions to it.

**Closed by SteveJobzniak** 2017-05-29 15:15 UTC

**Comment by matthijsotterloo** [comment] 2017-05-29 15:16
Woohoo! Excellent job @valga. 
Thanks @SteveJobzniak

**Comment by matthijsotterloo** [comment] 2017-05-29 17:25
@valga There's a bug in the code I think. When I do the following:
`
$direct = $ig->direct->getInbox();
$threads = $direct->inbox->threads;

foreach ($threads as $thread) {
    $items = $thread->items;
    $i++;

    $last = $thread->last_activity_at; 

    foreach ($items as $item) {
        $type = $item->item_type;
        if ($type == 'text') {
            $text = $item->text;
        }
    }
}
`

It seems like that the items array only contains 1 item even though there were multiple messages sent in the chat.

**Comment by matthijsotterloo** [comment] 2017-05-29 17:27
Small addition to the previous comment, I checked by printing the JSON response and it only shows 1 item in the items array.

**Comment by SteveJobzniak** [comment] 2017-05-29 17:34
@matthijsotterloo 

> Small addition to the previous comment: I checked by printing the JSON response and it only shows 1 item in the items array.

Yes. We show what the server sends us, so it's not a bug. ;)

**Comment by SteveJobzniak** [comment] 2017-05-29 19:08
@matthijsotterloo Did you try `$ig->direct->getThread()` yet? Do that.

**Comment by matthijsotterloo** [comment] 2017-05-31 18:55
@SteveJobzniak Yes, that works! Is there a way to view disappearing photos aswell?
