### ISSUE TITLE
bug report 

### ISSUE THREAD

**Issue by OwlGreenApple** [mgp25/Instagram-API#1113] opened 2017-03-23 03:58 UTC
## PLEASE FOLLOW THE GUIDE BELOW, OTHERWISE WE WILL DELETE YOUR TICKET WITHOUT ANSWERING IT

Hei i got error when trying to login with dev-master 335d212
im using sql to put cookies
the error says 
SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'username_id' at row 1
The data is saved but username_id is null

**Comment by SteveJobzniak** [comment] 2017-03-23 04:11
@OwlGreenApple Delete your MySQL database/table. Then try again. If the problem remains, show me the code where you are doing setUser().

**Comment by SteveJobzniak** [comment] 2017-03-23 04:15
I know what the problem is now.

**Comment by SteveJobzniak** [comment] 2017-03-23 04:16
The MySQL backend was super sloppy and written like a monkey. I do not use it myself and have only done general cleanup on it. But yeah it doesn't properly handle unsetting username id here:

https://github.com/mgp25/Instagram-API/blob/master/src/Instagram.php#L204

**Comment by SteveJobzniak** [comment] 2017-03-23 04:16
If anyone wants to fix that, feel free. I am not going to touch the MySQL backend.

**Comment by SteveJobzniak** [comment] 2017-03-23 04:19
Meh, I had a look anyway. The problem is the MySQL table's column definitions. They are using a BIGINT where it should have been a string. I'll fix it.

**Comment by SteveJobzniak** [comment] 2017-03-23 04:19
In fact, every field must be strings. Nothing but strings can be stored in settings backends. So I'll add a comment about that for future contributors.

**Comment by SteveJobzniak** [comment] 2017-03-23 06:31
@OwlGreenApple This will get done later today. I will close this ticket for now. Don't worry.

**Closed by SteveJobzniak** 2017-03-23 06:31 UTC

**Comment by OwlGreenApple** [comment] 2017-03-23 06:47
Ok you are the best @SteveJobzniak
