### ISSUE TITLE
change photo upload configuration

### ISSUE THREAD

**Issue by mehmetks** [mgp25/Instagram-API#3096] opened 2020-01-07 16:36 UTC
# Bug Report

Internal.php
   - uploadSinglePhoto()
```php
   // Perform the upload.
  //$this->uploadPhotoData($targetFeed, $internalMetadata); remove this line
  $this->_uploadResumablePhoto($targetFeed, $internalMetadata);
  // Configure the uploaded image and attach it to our timeline/story.
  $configure = $this->configureSinglePhoto($targetFeed, $internalMetadata,$externalMetadata);
  return $configure;
```
works fine for single photo upload. Instagram don't use upload/photo/ endpoint
![Screenshot_1](https://user-images.githubusercontent.com/59464222/71911430-b926e700-3184-11ea-814f-0f1e1f7cdd1e.png)

**Comment by JRoy** [comment] 2020-01-09 17:51
Duplicate of #2972

**Closed** 2020-01-09 17:51 UTC
Labels: duplicate
