### ISSUE TITLE
Using API to check login and password

### ISSUE THREAD

**Issue by mashkovtsevlx** [mgp25/Instagram-API#1658] opened 2017-10-27 20:04 UTC
Hello. 
I want to use API for checking username and password correctness, but api saves session everytime and if i type wrong password, it logins anyway. How can I check username and pass using your API? 
I tried 'logout()' after every login, but it doesn't help.

Thank You

**Comment by itsMoji** [comment] 2017-10-27 20:31
@mashkovtsevlx 
You should use force login
try this:
`$ig->login($username, $password,`**true**`);`

**Comment by mashkovtsevlx** [comment] 2017-10-27 20:43
@itsMoji Thank You for a reply.
Didn't help. Here's a code (Rewrited example)
```php
<?php
set_time_limit(0);
date_default_timezone_set('UTC');

require __DIR__.'/../../modules/php/vendor/autoload.php';

/////// CONFIG ///////
$username = '***';
$password = '***';
$debug = false;
$truncatedDebug = false;
//////////////////////

$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);

try {
    $loginResponse = $ig->login($username, $password);
    if ($loginResponse !== null)
    {
        echo("Login");
    }
    if ($loginResponse !== null && $loginResponse->isTwoFactorRequired()) {
        echo "2Factor";
        $twoFactorIdentifier = $loginResponse->getTwoFactorInfo()->getTwoFactorIdentifier();

        // The "STDIN" lets you paste the code via terminal for testing.
        // You should replace this line with the logic you want.
        // The verification code will be sent by Instagram via SMS.
        $verificationCode = trim(fgets(STDIN));
        $ig->finishTwoFactorLogin($verificationCode, $twoFactorIdentifier);
    }
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    echo 'Out';
}
$ig->login($username, $password,true);
```

**Comment by mashkovtsevlx** [comment] 2017-10-27 20:51
@itsMoji Thank you for a reply.
It sounds weird, but if I'm using a password with one extra character (wrong password) in the front or end, "echo "Login"" displays. If i use wrong password with two/more extra wrong characters, it displays an exception (bad login).
Here's a code (Rewrited example).
```php
<?php
set_time_limit(0);
date_default_timezone_set('UTC');

require __DIR__.'/../../modules/php/vendor/autoload.php';

/////// CONFIG ///////
$username = '***';
$password = 'HondaCBR600MOTO3';
$debug = false;
$truncatedDebug = false;
//////////////////////

$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);

try {
    $loginResponse = $ig->login($username, $password,true);
    if ($loginResponse !== null)
    {
        echo("Login");
    }
    if ($loginResponse !== null && $loginResponse->isTwoFactorRequired()) {
        echo "2Factor";
        $twoFactorIdentifier = $loginResponse->getTwoFactorInfo()->getTwoFactorIdentifier();

        // The "STDIN" lets you paste the code via terminal for testing.
        // You should replace this line with the logic you want.
        // The verification code will be sent by Instagram via SMS.
        $verificationCode = trim(fgets(STDIN));
        $ig->finishTwoFactorLogin($verificationCode, $twoFactorIdentifier);
    }
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    echo 'Out';
}
```

**Comment by itsMoji** [comment] 2017-10-27 21:32
@mashkovtsevlx i've tested your code and you're right.

**Comment by itsMoji** [comment] 2017-10-27 21:38
@mashkovtsevlx i've tested your code and you're right.
The API will login successful with **one extra character on front or end** even on first login and session folder doesn't exist! 
@mgp25 
@SteveJobzniak

**Comment by mohammadhosin** [comment] 2017-10-27 22:50
change password to simple character

**Comment by mashkovtsevlx** [comment] 2017-10-28 00:09
@mohammadhosin It's simple-character

**Comment by valga** [comment] 2017-10-28 06:33
> The API will login successful with one extra character on front or end.

The app does the same, so it is not an issue.

**Comment by SteveJobzniak** [comment] 2017-10-28 07:53
Lol guys, I wish you would search:

https://github.com/mgp25/Instagram-API/issues?utf8=✓&q=is%3Aissue%20is%3Aclosed%20password%20character

**Comment by SteveJobzniak** [comment] 2017-10-28 07:54
Duplicate of #1279

**Comment by SteveJobzniak** [comment] 2017-10-28 07:58
Now, to address the _new_ part of this ticket, about "wanting to check password validity":

> I want to use API for checking username and password correctness, but api saves session everytime and if i type wrong password, it logins anyway. How can I check username and pass using your API?
I tried 'logout()' after every login, but it doesn't help.

Dude... please listen to me very carefully now:

- Do.
- Not.
- Do.
- _That._

;-)

This API emulates the Android application.

The Android (and iOS for that matter) apps log in to Instagram, register their "device ID", and then they stay logged in forever (until the user manually logs out, which normal users never do).

We save the session and all of its hardware device ID details, so that Instagram constantly sees the "same device" re-connecting.

If we DID NOT save the session, **YOU WOULD BE BANNED BY INSTAGRAM**.

They ban you after too many different device IDs have logged in to an account.

_That_ is why we save the session and all device hardware details and keep re-using them, _exactly like the real app_.

And as for the trick of calling `logout()`: If you do that, you look like a fake client, because no real users log out constantly between their uses.

As for the trick of calling `login(true)`: You also look fake, because you already have a valid session so they'll have to wonder "why force a re-login? the cookies and device ID we are seeing is already logged in!".

**Comment by SteveJobzniak** [comment] 2017-10-28 07:58
In short: The Android and iOS Instagram apps are not capable of "verify password on every attempt to use the app", and therefore _neither are we_. You cannot do it.

**Closed by SteveJobzniak** 2017-10-28 07:58 UTC

**Comment by SteveJobzniak** [comment] 2017-10-28 08:01
PS: @itsMoji The ability to "force login" is not really meant to be used by users of this API. It's an internal feature we use to force a re-login when we internally detect an expired session.

We kinda should make that variable private...... hmmm.

**Comment by SteveJobzniak** [comment] 2017-10-28 09:38
Forcelogin now removed: https://github.com/mgp25/Instagram-API/commit/6be6daef14e283a491927a92c06ca0f80debcb4f
