### ISSUE TITLE
API Request : Replies of comment

### ISSUE THREAD

**Issue by learningwithyou** [mgp25/Instagram-API#1624] opened 2017-10-18 00:16 UTC
I found this **$ig->media->getComments** but i want to list of replies of commentID.

Example of photo page.
You can check [as image](https://ibb.co/c0pOfm); 

> [ IMAGE ] 
> _caption of photo_
> 
> comment
> comment
> comment
>        --- reply 
>        --- **[see 10 replies ]** 
> comment
> comment
>        --- reply

I need api of page after click that **[see 10 replies ]** , can you help about this url ?

Thank you for helping.

**Comment by SteveJobzniak** [comment] 2017-10-18 21:18
You're probably right. That seems to be a new API they've recently added.

**Comment by valga** [comment] 2017-10-19 16:04
@learningwithyou You can file a PR if you want this feature.

Endpoint: `media/%s/comments/%s/child_comments/` where first `%s` is media ID and second one is parent comment ID.
Params: `max_id` (optional) - used for paging.

**Comment by SteveJobzniak** [comment] 2017-10-19 17:53
@valga Hi. This is my last day. I guess you saw the ticket where I came back due to being sick in bed with a fever. It's been more fun than just... doing absolutely nothing in bed. Anyway, I'd like to add the `getCommentReplies()` function after I am done with the final MediaAutoResizer things. Do you have the parameter captures (JSON dump)? I don't have any capture tools (I uninstalled everything when I left). The regular `getComments()` uses the following:

```php
        return $this->ig->request("media/{$mediaId}/comments/")
            ->addParam('ig_sig_key_version', Constants::SIG_KEY_VERSION)
            ->addParam('max_id', $maxId)
            ->getResponse(new Response\MediaCommentsResponse());
```

Is ig_sig_key_version included in the new one?

**Comment by valga** [comment] 2017-10-19 18:37
@SteveJobzniak Hi.
> Is ig_sig_key_version included in the new one?

Nope. And you should remove it from `getComments()`, because it is not a signed request. But you need to add `can_support_threading=true` there to receive threaded comments.

Here is a list of fields to add into `Comment` model:
```
'child_comment_count' => 'int',
'parent_comment_id' => 'string',
'preview_child_comments' => 'Comment[]',
'other_preview_users' => 'User[]',
```
And here is a response for `getCommentReplies()`:
```
'parent_comment' => 'Comment',
'child_comments' => 'Comment[]',
'next_min_child_cursor' => 'string',
'next_max_child_cursor' => 'string',
```

**Comment by SteveJobzniak** [comment] 2017-10-19 19:06
@valga Thanks, I'll add those soon. Almost done with the MediaAutoResizer rewrite (this evening), then I'll do it.

**Comment by learningwithyou** [comment] 2017-10-19 19:29
Thank you @valga and  @SteveJobzniak  for replying.

But how can i find "Comment Model ?" which  php is this for add  fields to into?

```
'child_comment_count' => 'int',
'parent_comment_id' => 'string',
'preview_child_comments' => 'Comment[]',
'other_preview_users' => 'User[]',

```

**Comment by SteveJobzniak** [comment] 2017-10-20 02:15
Implemented:

https://github.com/mgp25/Instagram-API/pull/1619/commits/e380adc4e7398d3cd378b4fa3215bb9746558139

https://github.com/mgp25/Instagram-API/pull/1619/commits/6ff1407148bf89cba4fe9b64c7a953a02803a31b

Note:

1. It's not merged yet.

2. Its not merged yet.

3. See 1 & 2. ;-)

**Comment by valga** [comment] 2017-10-20 05:55
@SteveJobzniak `http_build_query()` function has a secret feature: `null` values are ignored. For example:
```
php > var_dump(http_build_query(['max_id' => null]));
string(0) ""
```
However, it preserves empty strings:
```
php > var_dump(http_build_query(['max_id' => '']));
string(7) "max_id="
```

**Comment by SteveJobzniak** [comment] 2017-10-20 08:42
@valga Ahh, but that is a terrible thing to rely on, especially since signing etc could have been involved. I will change it to a 'if, then addparam'. The only reason I changed it was because that was the only place innthe code whihc added maxid directly.

There are multiple places that add maxid via the method I just used (empty string). I guess those are all bad too. I'll take care of those too.

**Comment by SteveJobzniak** [comment] 2017-10-20 14:18
@valga Okay I've used `ag` to search for all bad codestyle blocks and rewrote them all to `!== null: addParam()` style.

https://github.com/mgp25/Instagram-API/pull/1619/commits/d080e23486616f574635361492b5874797ac0757

I'm mainly curious about Timeline and Usertag. As you can see, I changed it from _always_ adding an empty string (if no maxId provided), to now only sending it if it was provided.

Can you check your APK to make sure that's right? I really think the old code was a bug (always sending it empty), and that the new code is correct to only send maxId when provided.

**Comment by valga** [comment] 2017-10-20 20:03
> Can you check your APK to make sure that's right?

I can confirm that.

Also, `rank_token`, `ranked_content` and `min_timestamp` params are deprecated for `getUserFeed()` methods.

**Comment by SteveJobzniak** [comment] 2017-10-20 20:07
@valga Great, thanks a lot for checking! As for the deprecated params, those are up to mgp... who is still missing. I hope he's alive. xD

**Comment by SteveJobzniak** [comment] 2017-10-22 20:40
@learningwithyou Alright this is now merged to `dev-master` and can be used:

https://github.com/mgp25/Instagram-API/commit/dc6e0787f5579a785ae8a4262c0b3bb926da7db4

https://github.com/mgp25/Instagram-API/commit/5a0c3bdbc04560798cd0259740730b5bfe6aae95

😄

**Closed by SteveJobzniak** 2017-10-22 20:40 UTC

**Comment by etmatrix** [comment] 2018-03-08 10:55
> Also, rank_token, ranked_content and min_timestamp params are deprecated for getUserFeed() endpoints.

Today I tried to use the param min_timestamp and is still working.
I think the good way for deprecated functions or deprecated params is set a warning and not remove it.

**Comment by valga** [comment] 2018-03-08 12:05
@etmatrix Well, we are trying to emulate most recent versions of the real app, and they don't use that `min_timestamp` parameter anymore. So we have to remove it as well.

But in the same time Instagram cares about old versions, and `min_timestamp` works for them. So you have only 2 valid options:
1) use old versions that have `min_timestamp`. It is obvious that old versions don't have new features, and are going to be deprecated sooner or later;
2) use recent versions. They don't have `min_timestamp`, so you have to do some work around that.

Your proposal for using recent version+old params is invalid, because no real app does that, so you may be flagged based on that.

To conclude, you have to adapt, because nothing lasts forever.
