### ISSUE TITLE
Uploaded photo still can't be shared by direct message

### ISSUE THREAD

**Issue by rpw98** [mgp25/Instagram-API#73] opened 2016-03-03 13:49 UTC
It always shows "This photo is unavailable right now"...

**Comment by RageBrahimi** [comment] 2016-03-05 16:50
It's a similar case scenario when you try find an uploaded image (using this API) on a hashtag. It seems Instagram can detect it's not uploaded natively therefore it's probably restricted.

**Comment by mgp25** [comment] 2016-03-05 18:34
@rpw98 i'll fix that eventually, i know where the issue is

Maybe in next release will be fixed

Regards

**Closed by mgp25** 2016-03-05 18:34 UTC

**Comment by rpw98** [comment] 2016-03-05 18:38
@mgp25 Thank you! can't wait for the update!

**Comment by sinnus** [comment] 2016-04-12 08:33
@mgp25 can you tell where problem is?
Thank you.

**Comment by rpw98** [comment] 2016-04-19 18:59
@mgp25 have you found time to fix it? Or would you mind giving a hint on how to fix it?
Thank you!

**Comment by mgp25** [comment] 2016-04-19 19:39
@rpw98 right now im very busy with exams and i wont be free again for 1 month or so :/ if no one update this i'll do it eventually when i have free time

Regards
