### ISSUE TITLE
Instagram Blocks For Following/Unfollowing

### ISSUE THREAD

**Issue by Rosenkreuzer** [mgp25/Instagram-API#854] opened 2017-01-16 08:01 UTC
Hello, guys, I wrote a script which goes through txt file of user_id's and follow's users. 

After one minute I got banned. If I add random timeout after every request it still happens. 

Is it solution for that? 

Does proxy help ? If yes, should I connect each time with different proxy Ip for each request?

I hope, you understand, what I'm talking about and please help me :)

I want to have lot of followers :)

**Comment by ping** [comment] 2017-01-16 09:51
Duplicate of #802
Please search before submitting an issue.

**Closed by ping** 2017-01-16 09:51 UTC
Labels: duplicate
