### ISSUE TITLE
Not eligible error

### ISSUE THREAD

**Issue by filippofinke** [mgp25/Instagram-API#2874] opened 2019-09-16 16:40 UTC
### Before submitting an issue make sure you have:
- [ X] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ X] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [X ] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [X ] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ X] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [X ] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ X] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.
 Code:

```
<?php
require __DIR__.'/../vendor/autoload.php';

$ig = new \InstagramAPI\Instagram(true, false, [
    'storage'    => 'file',
    'basefolder' => 'storage',
]);

try {
    $ig->login("username","password");
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}
?>
```

RESPONSE: {"message": "not eligible", "status": "fail"}

Something went wrong: InstagramAPI\Response\GenericResponse: Not eligible.
```

### Describe your issue

I am getting Not eligible trying to log in.

**Comment by molnarviktor86** [comment] 2019-09-16 17:02
Same here

**Comment by JRoy** [comment] 2019-09-16 17:02
Can you please send a debug log?

**Comment by filippofinke** [comment] 2019-09-16 17:07
I resolved the problem allowing the login from the instagram application and waited 5 minutes.
I also used the non in development version (idk if this is correlated)

**Comment by JRoy** [comment] 2019-09-16 18:15
Gonna leave this open for now, if someone encounters this issue please send a censored debug log, thanks!

**Comment by frmeran** [comment] 2019-09-16 20:43
I'm having the same issue.

**Comment by JRoy** [comment] 2019-09-16 21:40
I think I've found the root cause of this issue, expect a fix within a day

**Comment by JRoy** [comment] 2019-09-17 01:24
Should be fixed as of https://github.com/mgp25/Instagram-API/commit/7f7718701e9b12ffc97105097aa0af00a74b2247

Release v7.0.1 also includes this fix :P

Cheers!

**Closed by JRoy** 2019-09-17 01:24 UTC
Labels: bug, fixed
