### ISSUE TITLE
API - Post (photo, video, story) not working

### ISSUE THREAD

**Issue by cyDevMs** [mgp25/Instagram-API#3023] opened 2019-11-21 14:31 UTC
# Bug Report

---

### Notes:
We will close your issue, sometimes without answering, if any of the following are met:
* You have not included your code or your debug log
* You are asking about `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
* You have used the wrong issue template
* You are posting screenshots, which are too painful to help you with 

Please make sure you have done the following before submitting your issue:
* You have [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bug-tracker for similar issues including **closed** ones
* You have [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
* You have [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
* You have [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
* You have [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
* You are [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

---

### Description
Please include a well-worded description of your issue below; We will close your issue if we have to guess what you're talking about, please be as specific as possible:

Instagram responding with "400 Something is wrong. Please check your input and try again." again.

The issue rised last week again and is present still then. I would love to know if there is a fix on the way or if this api is dead with whatever Instagram did.

**Comment by michelmelo** [comment] 2019-11-21 14:55
#3014 
your problem and many others

**Comment by michelmelo** [comment] 2019-11-21 14:56
is running instagram which is blocking the people using the api.

**Comment by cyDevMs** [comment] 2019-11-21 15:05
I know that that many have the issue.
The question is, can i wait for a fix or no fix possible in the futur so i need to go on

**Comment by JRoy** [comment] 2019-11-21 15:12
Duplicate of #2972

**Closed** 2019-11-21 15:12 UTC
Labels: duplicate, invalid
