### ISSUE TITLE
getFullResponse no longer working

### ISSUE THREAD

**Issue by michaeldprice** [mgp25/Instagram-API#1626] opened 2017-10-18 19:58 UTC
Hello.

I setup my application a couple of weeks ago to use the following for exception handling.

`catch (InstagramAPI\Exception\ChallengeRequiredException $e) {
			if ($e->hasResponse()) {
       			$response = $e->getResponse()->getFullResponse();`

However that code is now throwing guzzle exceptions, stating that getFullResponse() is not a function.

I also get errors using ->setUser();
Call to undefined method InstagramAPI\Instagram::setUser() 

What happened?

**Comment by michaeldprice** [comment] 2017-10-18 20:14
More errors ...

`<b>Fatal error</b>:  Uncaught Error: Call to undefined function InstagramAPI\Media\exif_read_data() in /home/socialschedule/public_html/app/Vendors/instagram/vendor/mgp25/instagram-php/src/Media/PhotoResizer.php:203
Stack trace:
#0 /home/socialschedule/public_html/app/Vendors/instagram/vendor/mgp25/instagram-php/src/Media/PhotoResizer.php(84): InstagramAPI\Media\PhotoResizer-&gt;_loadImageDetails()
#1 /home/socialschedule/public_html/app/Vendors/instagram/vendor/mgp25/instagram-php/src/MediaAutoResizer.php(297): InstagramAPI\Media\PhotoResizer-&gt;__construct('/home/socialsch...', '/tmp', Array)
#2 /home/socialschedule/public_html/app/ajax/igPost.php(152): InstagramAPI\MediaAutoResizer-&gt;__construct('/home/socialsch...')
#3 {main}
  thrown in <b>/home/socialschedule/public_html/app/Vendors/instagram/vendor/mgp25/instagram-php/src/Media/PhotoResizer.php</b> on line <b>203</b><br />
`

**Comment by SteveJobzniak** [comment] 2017-10-18 21:13
Sigh. You have committed a million mistakes and wasting our time with those. The only error is your lazy behavior.

1. Using `dev-master`, which we warn against, since it is an undocumented (no release notes yet) in-dev version for _PROFESSIONALS_ with a brain: https://github.com/mgp25/Instagram-API#using-composer

> If you want to test new and possibly unstable code that is in the master branch, and which hasn't yet been released, then you can use master instead (**at your own risk**).

2. Using `dev-master` and not freaking searching the commits yourself, and instead wasting our time by asking us about it. Here is your `getFullResponse()` answer: https://github.com/mgp25/Instagram-API/commit/b48277ef1428edf3f842b7519177818e2cc022d0

3. Not even reading the release notes for our documented full releases, where we talk about `setUser()`: https://github.com/mgp25/Instagram-API/releases/tag/v3.0.0

4. Making the typical Composer idiot mistake of installing on System A (which successfully has the `exif` extension) and moving to System B (where you lack the `exif` extension). You are the reason why the exif error is happening. Not us. As the readme explains: https://github.com/mgp25/Instagram-API#warning-about-moving-data-to-a-different-server

> #### _Warning about moving data to a different server_

> _Composer checks your system's capabilities and selects libraries based on your **current** machine (where you are running the `composer` command). So if you run Composer on machine `A` to install this library, it will check machine `A`'s capabilities and will install libraries appropriate for that machine (such as installing the PHP 7+ versions of various libraries). If you then move your whole installation to machine `B` instead, it **will not work** unless machine `B` has the **exact** same capabilities (same or higher PHP version and PHP extensions)! Therefore, you should **always** run the Composer-command on your intended target machine instead of your local machine._

Why am I giving you this attitude? Because I spend months and months coding the code that you are using. You spend 0 seconds even checking your mistakes before dumping this crap on us to make us waste time explaining your mistakes to you. I am close to saying the F-word but I don't want to be rude to an ungrateful, useless monkey.

Enjoy the answers I just gave you. You're worth it.

Make more effort next time, if there is a next time.

**Comment by michaeldprice** [comment] 2017-10-18 21:40
While I understand your frustration, especially with an open project like
this, your a bit off on a few things.

The ONLY reason why I used dev-master, was becuase mgp25 told me to, since
i was using examples from it.

While there may be areas of programming that I am not experienced, I am
still a professional.

While coding in php for over 10 years, this is the first time I have ever
used composer. So , sure Im unexperienced in it.
Along with any of the http parsers.

"Making the typical Composer idiot mistake of installing on System A (which
successfully has the exif extension) and moving to System B (where you lack
the exif extension). You are the reason why the exif error is happening.
Not us. As the readme explains: https://github.com/mgp25/
Instagram-API#warning-about-moving-data-to-a-different-server

That is just completely FALSE.

While I did move servers, I reinstalled all my projects that use composer,
using composer.

After a few attempts, I did get it working using

composer require mgp25/instagram-php


HOWEVER the exif error STILL exists.

I am also not a rude, or ungrateful person, Let alone, a monkey.

Opinions, so be it.

Considering the fact that all of you have put so many hours into this
project, as a sign of appreciation, Im going to ignore the false claims,
name calling, and overall approach.

As stated, even with a fresh install of the script, using composer, I still
get the exif error.



Wishing you the best,
Michael D Price

http://facebook.com/michaeldprice
http://www.linkedin.com/in/michaelpricejr


---------------------------------------------------------------------------------------------------------------------------
Blatant Advertisement

If you're an affiliate marketer and your NOT using Free Link Cloaker you
Are Losing Money!

Download Your Free Copy Today, Before It's To Late!

http://FreeLinkCloaker.com
-----------------------------------------------------------------------------------------------------------------------

**Comment by michaeldprice** [comment] 2017-10-18 21:46
FYI: Donation Send. We all get frustrated, but come on ...

Wishing you the best,
Michael D Price

http://facebook.com/michaeldprice
http://www.linkedin.com/in/michaelpricejr


---------------------------------------------------------------------------------------------------------------------------
Blatant Advertisement

If you're an affiliate marketer and your NOT using Free Link Cloaker you
Are Losing Money!

Download Your Free Copy Today, Before It's To Late!

http://FreeLinkCloaker.com
-----------------------------------------------------------------------------------------------------------------------

**Comment by SteveJobzniak** [comment] 2017-10-18 21:51
Wow, I take back what I said. You're displaying intelligence in those sentences.

Alright, so on to the issue:

```
    "require": {
        "php": ">=5.6",
        "lazyjsonmapper/lazyjsonmapper": "^1.3.0",
        "guzzlehttp/guzzle": "^6.2",
        "ext-curl": "*",
        "ext-mbstring": "*",
        "ext-gd": "*",
        "ext-exif": "*", <----------------------
        "ext-zlib": "*",
        "react/event-loop": "^0.4.3",
        "react/promise": "^2.5",
        "react/socket": "^0.8",
        "binsoul/net-mqtt-client-react": "^0.3.2",
        "clue/socks-react": "^0.8.2",
        "clue/http-proxy-react": "^1.1.0",
        "psr/log": "^1.0",
        "valga/fbns-react": "^0.1.7"
    },
```

There is absolutely no way to install this library without having EXIF installed.

So most likely what's happening is a separate issue:

Imagine this:

```
$ ssh someserver

someserver $ which php
/usr/local/bin/php

someserver $ php -r "var_dump(extension_loaded('exif'));"
bool(true)

someserver $ composer require mgp25/instagram-php
... installs successfully, because Composer sees that your php binary has 
```

Now run `http://someserver/foo.php`... and... ERROR! WHY!?!?!?

Because Apache / Nginx (or whatever server you're using) has its own PHP binary which is NOT the same one as the command line one used by Composer. And the Apache one does NOT have the exif extension.

You can verify this with a script:

```php
testme.html.php
<?php

var_dump(extension_loaded('exif'));
```

As for how we're coding the exif-function call, which is making it appear in your error log as `Call to undefined function InstagramAPI\Media\exif_read_data()`, that's because it is a builtin PHP function so we do not need to prefix it with `\exif_read_data()` if the extension IS loaded. Which it always is if the user has installed it properly via Composer (which verifies that they have PHP).

We do not recommend running these scripts directly as the web app by the way. Read this wiki entry I wrote a few days ago: https://github.com/mgp25/Instagram-API/wiki/FAQ#if-the-error-500-happens-in-a-web-browser-when-you-host-a-script-that-uses-this-library

**Comment by SteveJobzniak** [comment] 2017-10-18 21:54
Just saw your message about the donation and the message in it. I definitely had you wrong. Sorry about that. The things you spoke about and the pattern was just so similar to all the ignorant hordes I've had to deal with month in and month out. But your English is way too intelligent to be one of those dumb people. ;-)

**Comment by SteveJobzniak** [comment] 2017-10-18 22:05
Oh about `getFullResponse()`. I wasn't going to answer that when I thought you were lazy.

Its only purpose was to read properties that did not exist in the core Response/Model objects. But reading such properties is now supported natively in v4.x (the dev-master work) thanks to my new LazyJsonMapper library. If you go [to its official page](https://github.com/SteveJobzniak/LazyJsonMapper), and [check out this ticket](https://github.com/mgp25/Instagram-API/issues/1623) where I gave users some tips, then you can learn more about it and what it will offer you.

If you were going to use that feature, the new way to read "non-existent" properties it is this:

- Imagine that the property name is `some_property`.
- You can access it via its automatic LazyJsonMapper functions: `hasSomeProperty()`, `isSomeProperty()`, `getSomeProperty()`, `setSomeProperty()` and `unsetSomeProperty()`.
- To learn about those functions, you don't have to memorize their names. You can just use `$response->printPropertyDescriptions()`, which runs with default options "show functions, do not allow relative types, do not show undefined properties".
- To do the same listing, but include undefined proproperties that only exist in the data, use `$response->printPropertyDescriptions(true, false, true)`. (Functions on, relative off, undefined on).
- Now that you have the function name, you should realize something... If you simply call `getSomeProperty()` as if it was a regular, fully defined property, then it _will_ work _if_ the property exists in the current object's data, but it will throw an exception if it doesn't exist. Because unmapped (undefined) properties will warn in that case. So that's dangerous.
- There's a special function for that purpose: `hasSomeProperty()`. It never throws exceptions. And it returns TRUE if the property either exists in the JSON data and/or has a full definition.

So here's your code for reading `some_property`:

- Old code: `if ($x->getFullResponse()->some_property()) { ... }`

- New code (and assuming it's a flag, you can and should use `isX` to check if it's a "true"-like value; otherwise just use `getX` as usual if you want to actually get its value): `if ($x->hasSomeProperty() && $x->isSomeProperty()) { ... }`

**Comment by michaeldprice** [comment] 2017-10-18 22:10
Thank you.

Running the extension_loaded for exif returns false.

When running composer it returns the following.
-----------------------------------------------------------------
[socialschedule@host instagram]$ composer require mgp25/instagram-php
Using version ^3.1 for mgp25/instagram-php
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 22 installs, 0 updates, 0 removals
  - Installing react/event-loop (v0.4.3): Loading from cache
  - Installing evenement/evenement (v2.1.0): Loading from cache
  - Installing react/stream (v0.7.4): Loading from cache
  - Installing react/promise (v2.5.1): Loading from cache
  - Installing react/promise-timer (v1.2.0): Loading from cache
  - Installing react/socket (v0.8.4): Loading from cache
  - Installing react/dns (v0.4.11): Loading from cache
  - Installing react/cache (v0.4.1): Loading from cache
  - Installing psr/log (1.0.2): Loading from cache
  - Installing binsoul/net-mqtt (0.2.1): Loading from cache
  - Installing valga/fbns-react (0.1.8): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing ringcentral/psr7 (1.2.1): Loading from cache
  - Installing clue/http-proxy-react (v1.2.0): Loading from cache
  - Installing clue/socks-react (v0.8.6): Loading from cache
  - Installing binsoul/net-mqtt-client-react (0.3.2): Loading from cache
  - Installing guzzlehttp/psr7 (1.4.2): Loading from cache
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing guzzlehttp/guzzle (6.3.0): Loading from cache
  - Installing netresearch/jsonmapper (v1.3.0): Loading from cache
  - Installing mgp25/instagram-php (3.1): Loading from cache
  - Installing lazyjsonmapper/lazyjsonmapper (v1.2.4): Loading from cache
react/event-loop suggests installing ext-libevent (>=0.1.0)
react/event-loop suggests installing ext-event (~1.0)
react/event-loop suggests installing ext-libev (*)
valga/fbns-react suggests installing ext-event (For more efficient event
loop implementation.)
valga/fbns-react suggests installing ext-gmp (To be able to run this code
on x86 PHP builds.)
mgp25/instagram-php suggests installing ext-event (Installing PHP's native
Event extension enables faster Realtime class event handling.)
Generating autoload files


As for the web browser reference, I dont run the script itself in a browser
exactly ...

I use the script from 2 different processes.
1. php-cli
2. AJAX call from a browser.

**Comment by SteveJobzniak** [comment] 2017-10-18 22:18
Good design. AJAX call from a browser to a static CLI process is a good pro-level setup. ;-)

You can also look at the `realtimeHttp` example for how to make an internal API server that can sit and accept queries. Although it'd be similar to your AJAX setup.

As for the composer stuff: That's so weird. Look, if you make an empty folder and put this `composer.json` in it:

```
{
    "require": {
        "ext-foopfoopfoop": "*"
    }
}
```

And run `composer install`. You will see:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-foopfoopfoop * is missing from your system. Install or enable PHP's foopfoopfoop extension.


```

The same should be seen for your `exif` extension.

So the only answer is that _WHICHEVER_ PHP process Composer is using, _that_ one _does_ have the EXIF extension. But _NOT_ the one that's running your CLI.

So I think the answer is that you're calling something like `php yoursscript.php`, whereas Composer does something like `/usr/bin/env php`. The difference is that one uses overridden PATH and one uses system PATH.

Try that.

**Comment by SteveJobzniak** [comment] 2017-10-18 22:26
You know what... quite recently I added a PHP 5.6 check to the constructor of this library, to make it quit if the user didn't have PHP 5.6. Because tons of people install it with Composer on computer A, and move it to B with 5.4 or something.

That ended all of those incoming tickets.

But it would actually be a good idea to also add some constructor-checks for all of our required extensions. It would have caught your strange situation in an easier way and that's always nice, since yours was an honest mistake (your server has lots of different PHP binaries and php.ini's with differing extensions in each).

I am going to add such checks. They won't be perfect (I am not gonna go through the whole tree of all of our externally depended libraries to see what they need too), but they will help with the most egregious examples like exif (which has bit others in the past too). And anything to help reduce tickets from people who just copy their vendor-dir from their home PC to their less-equipped server will make us happier. ;-)

**Comment by michaeldprice** [comment] 2017-10-18 22:38
This is a bit odd.

[socialschedule@host /]$ which php
/usr/local/bin/php

[socialschedule@host /]$ php -r "var_dump(extension_loaded('exif'));"
bool(true)

[root@host /]# php -d display_errors
/home/socialschedule/public_html/app/cron/cron.php
bool(false)

cron.php file
<?php
#/usr/local/bin/php
var_dump(extension_loaded('exif'));
die();


so when i check if exif is loaded from the promp i get true, but when
running from a file via the prompt, i get false ;/


Wishing you the best,
Michael D Price

http://facebook.com/michaeldprice
http://www.linkedin.com/in/michaelpricejr


---------------------------------------------------------------------------------------------------------------------------
Blatant Advertisement

If you're an affiliate marketer and your NOT using Free Link Cloaker you
Are Losing Money!

Download Your Free Copy Today, Before It's To Late!

http://FreeLinkCloaker.com
-----------------------------------------------------------------------------------------------------------------------

**Comment by SteveJobzniak** [comment] 2017-10-18 22:42
Hmm. Your file (which fails) specifies a full path to PHP. Try the same path on the command line to see what that one says:

`$ /usr/local/bin/php -r "var_dump(extension_loaded('exif'));"`

**Comment by michaeldprice** [comment] 2017-10-18 22:44
returns true ...

Wishing you the best,
Michael D Price

http://facebook.com/michaeldprice
http://www.linkedin.com/in/michaelpricejr


---------------------------------------------------------------------------------------------------------------------------
Blatant Advertisement

If you're an affiliate marketer and your NOT using Free Link Cloaker you
Are Losing Money!

Download Your Free Copy Today, Before It's To Late!

http://FreeLinkCloaker.com
-----------------------------------------------------------------------------------------------------------------------

**Comment by SteveJobzniak** [comment] 2017-10-18 22:51
Okay so the problem is that your CRON job is running `php cron.php`. Which is ignoring that file's `#!/usr/local/bin/php` line and running it with whatever random PHP process it finds.

Change it to `chmod +x cron.php` and then just directly link to `/some/path/cron.php` to run it directly.

**Comment by michaeldprice** [comment] 2017-10-18 22:53
well, No.

Im not using the cron job jet. Right now, Im calling the script from the
command line, during testing.

Once testing is completed, than the process will be called from cron.


Wishing you the best,
Michael D Price

http://facebook.com/michaeldprice
http://www.linkedin.com/in/michaelpricejr


---------------------------------------------------------------------------------------------------------------------------
Blatant Advertisement

If you're an affiliate marketer and your NOT using Free Link Cloaker you
Are Losing Money!

Download Your Free Copy Today, Before It's To Late!

http://FreeLinkCloaker.com
-----------------------------------------------------------------------------------------------------------------------

**Comment by michaeldprice** [comment] 2017-10-18 22:54
To clarify, which isnt an issue in this case anyway,

I have two systems that run this script.

1. PHP CLI from cron. WIll be from cron, right now being called manually
from command line SSH.
Also
Ajax request from browser, to url where script resides. I guess I should
change this, and have it run from the cron as well.
But hasnt been an issue yet.

Wishing you the best,
Michael D Price

http://facebook.com/michaeldprice
http://www.linkedin.com/in/michaelpricejr


---------------------------------------------------------------------------------------------------------------------------
Blatant Advertisement

If you're an affiliate marketer and your NOT using Free Link Cloaker you
Are Losing Money!

Download Your Free Copy Today, Before It's To Late!

http://FreeLinkCloaker.com
-----------------------------------------------------------------------------------------------------------------------

**Comment by SteveJobzniak** [comment] 2017-10-18 23:18
You should be sure that you run it via `./cron.php` on the command line that. Not via `php cron.php` Because if you call php directly, you override its `#!` shebang line.

Is that it?

**Comment by michaeldprice** [comment] 2017-10-18 23:28
Doing that doesnt run it as php. I get all kinds of syntax errors. Assuming
bash I presume.

[socialschedule@host cron]$ ./cron.php
: No such file or directory
./cron.php: line 3: =: command not found
./cron.php: line 3: $'\r': command not found
./cron.php: line 4: syntax error near unexpected token `$msg'
'/cron.php: line 4: `function v($msg){






[socialschedule@host cron]$ cron.php
bash: cron.php: command not found

[socialschedule@host cron]$ php cron.php
Change working directory:/home/socialschedule/public_html/app/cron
Change working directory:/home/socialschedule/public_html/app/cron
Success
Success
Running Query:SELECT tbl_posts.*,tbl_users.password,tbl_projects.user_ID
FROM tbl_posts
INNER JOIN tbl_projects ON tbl_projects.project_ID = tbl_posts.project_ID
INNER JOIN tbl_users ON tbl_users.user_ID = tbl_projects.user_ID
WHERE schedule_datetime < 1508369209 and status = 0 ORDER BY
schedule_datetime ASC;
Running Query:SELECT tbl_posts.*,tbl_users.password,tbl_projects.user_ID
FROM tbl_posts
INNER JOIN tbl_projects ON tbl_projects.project_ID = tbl_posts.project_ID
INNER JOIN tbl_users ON tbl_users.user_ID = tbl_projects.user_ID
WHERE schedule_datetime < 1508369209 and status = 0 ORDER BY
schedule_datetime ASC;
have posts
have posts
loading user class
loading user class
success
success
loading security class
loading security class
success
success
loop posts
loop posts
generate response obj for Instagram
generate response obj for Instagram
loading Instagram php poster
loading Instagram php poster
PHP Fatal error:  Uncaught InstagramAPI\Exception\SettingsException: The
"/home/socialschedule/public_html/app/Vendors/instagram/vendor/mgp25/instagram-php/src/../sessions/"
folder is not writable. in
/home/socialschedule/public_html/app/Vendors/instagram/vendor/mgp25/instagram-php/src/Settings/Storage/File.php:351
Stack trace:
#0
/home/socialschedule/public_html/app/Vendors/instagram/vendor/mgp25/instagram-php/src/Settings/Storage/File.php(54):
InstagramAPI\Settings\Storage\File->_createFolder('/home/socialsch...')
#1
/home/socialschedule/public_html/app/Vendors/instagram/vendor/mgp25/instagram-php/src/Settings/StorageHandler.php(125):
InstagramAPI\Settings\Storage\File->openLocation(Array)
#2
/home/socialschedule/public_html/app/Vendors/instagram/vendor/mgp25/instagram-php/src/Settings/Factory.php(202):
InstagramAPI\Settings\StorageHandler->__construct(Object(InstagramAPI\Settings\Storage\File),
Array, Array)
#3
/home/socialschedule/public_html/app/Vendors/instagram/vendor/mgp25/instagram-php/src/Instagram.php(254):
Instagra in
/home/socialschedule/public_html/app/Vendors/instagram/vendor/mgp25/instagram-php/src/Settings/Storage/File.php
on line 351


Wishing you the best,
Michael D Price

http://facebook.com/michaeldprice
http://www.linkedin.com/in/michaelpricejr


---------------------------------------------------------------------------------------------------------------------------
Blatant Advertisement

If you're an affiliate marketer and your NOT using Free Link Cloaker you
Are Losing Money!

Download Your Free Copy Today, Before It's To Late!

http://FreeLinkCloaker.com
-----------------------------------------------------------------------------------------------------------------------

**Comment by michaeldprice** [comment] 2017-10-18 23:29
"Because if you call php directly, you override its #! shebang line."

Even if that was the case php which and the shebang are the same.

Wishing you the best,
Michael D Price

http://facebook.com/michaeldprice
http://www.linkedin.com/in/michaelpricejr


---------------------------------------------------------------------------------------------------------------------------
Blatant Advertisement

If you're an affiliate marketer and your NOT using Free Link Cloaker you
Are Losing Money!

Download Your Free Copy Today, Before It's To Late!

http://FreeLinkCloaker.com
-----------------------------------------------------------------------------------------------------------------------

**Comment by michaeldprice** [comment] 2017-10-18 23:30
Im gong to ask hosting support about this.

I can continue without the resizer function.

Wishing you the best,
Michael D Price

http://facebook.com/michaeldprice
http://www.linkedin.com/in/michaelpricejr


---------------------------------------------------------------------------------------------------------------------------
Blatant Advertisement

If you're an affiliate marketer and your NOT using Free Link Cloaker you
Are Losing Money!

Download Your Free Copy Today, Before It's To Late!

http://FreeLinkCloaker.com
-----------------------------------------------------------------------------------------------------------------------

**Comment by SteveJobzniak** [comment] 2017-10-18 23:34
> Even if that was the case

Yeah it's the case. Shebang only takes effect when called via `./thefile` as if it was an executable.

But yeah ask the hosting provider.

Speaking of the resizer... I'm doing so much work on it... tons of work... a major rewrite. It's nearly done... You can track the commits here as they keep coming in: https://github.com/mgp25/Instagram-API/pull/1619/commits

**Comment by michaeldprice** [comment] 2017-10-18 23:44
Thanks for all the assistance.

If you were willing, what would you charge me to implement the ability to
complete the challange logins from within the script window?
Im considering having that ability, but not sure.

Wishing you the best,
Michael D Price

http://facebook.com/michaeldprice
http://www.linkedin.com/in/michaelpricejr


---------------------------------------------------------------------------------------------------------------------------
Blatant Advertisement

If you're an affiliate marketer and your NOT using Free Link Cloaker you
Are Losing Money!

Download Your Free Copy Today, Before It's To Late!

http://FreeLinkCloaker.com
-----------------------------------------------------------------------------------------------------------------------

**Comment by SteveJobzniak** [comment] 2017-10-19 00:00
Hi Michael. There are two areas that are forbidden: Account registration, and challenges. They're used as spammer circumvention (even though there are legitimate uses too). So unfortunately you'll find that nobody on the project will implement that. Sorry. :-\

**Comment by michaeldprice** [comment] 2017-10-19 00:07
I wasnt looking for automation.

I was just looking for user interaction that allows them to click the send
challenge code button.
Than user manually goes to their email, gets the code, and manually enters
the code in the challenge code.

Either way, I respect your decision. Thanks again.

Wishing you the best,
Michael D Price

http://facebook.com/michaeldprice
http://www.linkedin.com/in/michaelpricejr


---------------------------------------------------------------------------------------------------------------------------
Blatant Advertisement

If you're an affiliate marketer and your NOT using Free Link Cloaker you
Are Losing Money!

Download Your Free Copy Today, Before It's To Late!

http://FreeLinkCloaker.com
-----------------------------------------------------------------------------------------------------------------------

**Comment by SteveJobzniak** [comment] 2017-10-19 00:46
Basically the challenge goes like this: The phone asks Instagram to let it solve the challenge. Instagram posts the challenge number to their email/SMS. Then the user types it in on the phone and the phone sends the code to Instagram to confirm it. The code is pointless without the 2nd half that submits it. And both use the same system, so I can't do the "just send it" part either, sorry. :-) Thanks for understanding.

**Closed** 2017-10-22 20:27 UTC
Labels: Not related, question
