### ISSUE TITLE
Possibly, realtimeClient example isn't working.

### ISSUE THREAD

**Issue by solomax2014** [mgp25/Instagram-API#1453] opened 2017-08-02 18:37 UTC
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

### Describe your issue

examples/realtimeClient.php isn't working properly. Debug log below.

---

### Debug log

```
[20:30:02] [rtc] starting mqtt client
[20:30:03] [mqtt] Setting up connection timer to 0.5 seconds
[20:30:03] [mqtt] Connecting to "edge-mqtt.facebook.com:443"
[20:30:08] [mqtt] Connection timed out after 5 seconds.
[20:30:08] [mqtt] Retrying connection attempt because of the error
[20:30:08] [mqtt] Existing reconnect timer has been cancelled
[20:30:08] [mqtt] Setting up connection timer to 1.0 seconds
[20:30:09] [mqtt] Connecting to "edge-mqtt.facebook.com:443"
[20:30:14] [mqtt] Connection timed out after 5 seconds.
[20:30:14] [mqtt] Retrying connection attempt because of the error
[20:30:14] [mqtt] Existing reconnect timer has been cancelled
[20:30:14] [mqtt] Setting up connection timer to 2.0 seconds
[20:30:16] [mqtt] Connecting to "edge-mqtt.facebook.com:443"
[20:30:21] [mqtt] Connection timed out after 5 seconds.
[20:30:21] [mqtt] Retrying connection attempt because of the error
[20:30:21] [mqtt] Existing reconnect timer has been cancelled
[20:30:21] [mqtt] Setting up connection timer to 4.0 seconds
[20:30:25] [mqtt] Connecting to "edge-mqtt.facebook.com:443"
[20:30:30] [mqtt] Connection timed out after 5 seconds.
[20:30:30] [mqtt] Retrying connection attempt because of the error
[20:30:30] [mqtt] Existing reconnect timer has been cancelled
[20:30:30] [mqtt] Setting up connection timer to 8.0 seconds
[20:30:38] [mqtt] Connecting to "edge-mqtt.facebook.com:443"
[20:30:43] [mqtt] Connection timed out after 5 seconds.
[20:30:43] [mqtt] Retrying connection attempt because of the error
[20:30:43] [mqtt] Existing reconnect timer has been cancelled
[20:30:43] [mqtt] Setting up connection timer to 16.0 seconds
[20:30:59] [mqtt] Connecting to "edge-mqtt.facebook.com:443"
[20:31:04] [mqtt] Connection timed out after 5 seconds.
[20:31:04] [mqtt] Retrying connection attempt because of the error
[20:31:04] [mqtt] Existing reconnect timer has been cancelled
[20:31:04] [mqtt] Setting up connection timer to 32.0 seconds
[20:31:36] [mqtt] Connecting to "edge-mqtt.facebook.com:443"
[20:31:41] [mqtt] Connection timed out after 5 seconds.
[20:31:41] [mqtt] Retrying connection attempt because of the error
[20:31:41] [mqtt] Existing reconnect timer has been cancelled
[20:31:41] [mqtt] Setting up connection timer to 64.0 seconds
[20:32:45] [mqtt] Connecting to "edge-mqtt.facebook.com:443"
[20:32:50] [mqtt] Connection timed out after 5 seconds.
...
```
And so on, doubling the timer seconds.

**Comment by mgp25** [comment] 2017-08-02 19:05
@solomax2014 are you using a proxy? It seems its your connection. Works fine.

```
[19:02:19] [rtc] starting mqtt client
GET:  https://i.instagram.com/api/v1/direct_v2/inbox/?persistentBadging=true&use_unified_inbox=true

[19:02:19] [rtc] Setting up timer for login() to 2073 seconds
[19:02:19] [mqtt] Setting up connection timer to 0.5 seconds
[19:02:20] [mqtt] Connecting to "edge-mqtt.facebook.com:443"
[19:02:25] [mqtt] Connection timed out after 5 seconds.
[19:02:25] [mqtt] Retrying connection attempt because of the error
[19:02:25] [mqtt] Existing reconnect timer has been cancelled
[19:02:25] [mqtt] Setting up connection timer to 1.0 seconds
[19:02:26] [mqtt] Connecting to "edge-mqtt.facebook.com:443"
[19:02:26] [mqtt] Connection has been established
[19:02:26] [mqtt] Connected to broker
[19:02:26] [mqtt] Setting up keepalive timer to 900.0 seconds
[19:02:26] [mqtt] Subscribing to pubsub topics ig/live_notification_subscribe/***, ig/u/v1/***
[19:02:26] [mqtt] Sending message {"sub":["ig/live_notification_subscribe/***","ig/u/v1/***"]} to topic /pubsub
[19:02:26] [mqtt] Subscribing to graphql topics 1/graphqlsubscriptions/17867973967082385/{"input_data": {"user_id":***}}
[19:02:26] [mqtt] Sending message {"sub":["1/graphqlsubscriptions/###/{\"input_data\": {\"user_id\":***}}"]} to topic /ig_realtime_sub

**Comment by solomax2014** [comment] 2017-08-02 19:15
@mgp25, I don't use proxy. But, maybe, antivirus can MITM https traffic. I disabled https traffic checking in antivirus (Kaspersky Internet Security 17.0.0.611(f)), but script is still failing.

**Comment by valga** [comment] 2017-08-03 08:03
@solomax2014 Try to change `CONNECTION_TIMEOUT` const from 5 to, for example, 20.

**Comment by solomax2014** [comment] 2017-08-03 08:11
@valga, the same thing. I changed the const, but connection timeout didn't changed:
```[10:07:50] [mqtt] Connection timed out after 5 seconds.```

**Comment by valga** [comment] 2017-08-03 08:35
Hmm, that error comes from MQTT client. It happens when network connection has been successfully established, but a broker did not respond to `CONNECT` packet in time.

So, `connect()` method here https://github.com/mgp25/Instagram-API/blob/8bc7a51724558ac3f0b6c5e918e356d2816895dd/src/Realtime/Client/Mqtt.php#L447 has an optional param `$timeout` (I did not use it). Try setting it to a bigger value.

If it will not help you, then most likely Instagram thinks that you are sending invalid or expired credentials. Do you run original or modified example?

**Comment by solomax2014** [comment] 2017-08-03 08:42
@valga, I run original example from dev-master branch. Output now is changed a bit:
```
[10:39:54] [rtc] starting mqtt client
[10:39:55] [mqtt] Setting up connection timer to 0.5 seconds
[10:39:55] [mqtt] Connecting to "edge-mqtt.facebook.com:443"
[10:40:11] [mqtt] DNS query for edge-mqtt.facebook.com failed: too many retries
[10:40:11] [mqtt] Retrying connection attempt because of the error
[10:40:11] [mqtt] Existing reconnect timer has been cancelled
[10:40:11] [mqtt] Setting up connection timer to 1.0 seconds
[10:40:12] [mqtt] Connecting to "edge-mqtt.facebook.com:443"
[10:40:27] [mqtt] DNS query for edge-mqtt.facebook.com failed: too many retries
[10:40:27] [mqtt] Retrying connection attempt because of the error
[10:40:27] [mqtt] Existing reconnect timer has been cancelled
[10:40:27] [mqtt] Setting up connection timer to 2.0 seconds
[10:40:29] [mqtt] Connecting to "edge-mqtt.facebook.com:443"
[10:40:44] [mqtt] DNS query for edge-mqtt.facebook.com failed: too many retries
[10:40:44] [mqtt] Retrying connection attempt because of the error
[10:40:44] [mqtt] Existing reconnect timer has been cancelled
[10:40:44] [mqtt] Setting up connection timer to 4.0 seconds
[10:40:48] [mqtt] Connecting to "edge-mqtt.facebook.com:443"
[10:41:03] [mqtt] DNS query for edge-mqtt.facebook.com failed: too many retries
[10:41:03] [mqtt] Retrying connection attempt because of the error
[10:41:03] [mqtt] Existing reconnect timer has been cancelled
[10:41:03] [mqtt] Setting up connection timer to 8.0 seconds
[10:41:11] [mqtt] Connecting to "edge-mqtt.facebook.com:443"
[10:41:26] [mqtt] DNS query for edge-mqtt.facebook.com failed: too many retries
[10:41:26] [mqtt] Retrying connection attempt because of the error
[10:41:26] [mqtt] Existing reconnect timer has been cancelled
<aborted>
```

**Comment by valga** [comment] 2017-08-03 08:53
Now you have a problem with DNS lookup. Realtime client uses Google's DNS `8.8.8.8`. Is it available to you? Try to change it to your ISP's DNS server.

**Comment by solomax2014** [comment] 2017-08-03 09:17
Changing DNS in network adapter settings didn't help. But I'm using router at home. So I tried to change settings there: didn't help.

**Comment by mgp25** [comment] 2017-08-06 15:50
@solomax2014 any update in this? It seems the issue is at your side. If you dont give an update in 2 days, the issue will be closed as it seems to be working fine (tested with some accounts and different enviroments and connections).

Regards

**Comment by solomax2014** [comment] 2017-08-06 18:29
@mgp25, I'll try to use a proxy. Maybe it will give me some details about errors.

**Comment by solomax2014** [comment] 2017-08-06 18:57
It's strange, but using it through Charles and setVerifySSL(false) was successful:
```
[20:41:20] [mqtt] Setting up connection timer to 0.5 seconds
[20:41:20] [mqtt] Connecting to "edge-mqtt.facebook.com:443"
[20:41:20] [mqtt] Connection has been established
[20:41:21] [mqtt] Connected to broker
[20:41:21] [mqtt] Setting up keepalive timer to 900.0 seconds
[20:41:21] [mqtt] Subscribing to pubsub topics ig/live_notification_subscribe/***, ig/u/v1/***
[20:41:21] [mqtt] Sending message {"sub":["ig/live_notification_subscribe/***","ig/u/v1/***"]} to topic /pubsub
```
I don't know if the notifications will appear, so I'll edit this comment if it will be good.

**Comment by valga** [comment] 2017-08-07 08:00
@solomax2014 I got the same error recently while testing various PHP builds. It is actually a bug in certain PHP versions for Windows. See https://github.com/reactphp/dns/issues/63#issuecomment-310295100 for more details.

**Comment by solomax2014** [comment] 2017-08-07 09:53
@valga, I'm using xampp on WIndows, which has PHP 7.0.9 VC14 x86.  So, my version has a bug, as I understand.

**Comment by valga** [comment] 2017-08-07 10:47
@solomax2014 Consider updating your PHP version. Or you can just use a proxy as workaround, because it will resolve the hostname without errors. `setVerifySSL(false)` is not required (unless you are doing a MITM).

**Comment by solomax2014** [comment] 2017-08-07 10:56
@valga, I said that I used Charles, so curl gives me CA error without a ```setVerifySSL(false)```. I'll update PHP and check again.

**Comment by solomax2014** [comment] 2017-08-07 11:11
@valga, updating to 7.1.8 works. Script is working fine. Thank you.

**Closed** 2017-08-07 11:12 UTC
