### ISSUE TITLE
Transaction timeout

### ISSUE THREAD

**Issue by jonnymike** [mgp25/Instagram-API#864] opened 2017-01-18 12:31 UTC
Hello,
With the newest version i'm having the "Transcode timeout" even I have tried "sleep()".
My code is working fine with other 2 accounts, but it got failed with 1 instagram account for the same video.
This is the response I am getting for this account 

```json
{"crop_original_size":[null,null],"crop_center":[0,0],"crop_zoom":1},"extra":{"source_width":null,"source_height":null}}
← 202 	 50B
RESPONSE: {"status": "fail", "message": "Transcode timeout"}
InstagramAPI\ConfigureResponse : Transcode timeout
```

**Comment by mgp25** [comment] 2017-01-18 13:40
@jonnymike make sure ffmpeg is working properly.

As you can see in your response, `crop_original_size` is `null` and it comes from https://github.com/mgp25/Instagram-API/blob/master/src/Instagram.php#L584

`$photo`  is taken using ffmpeg

Regards

**Comment by jonnymike** [comment] 2017-01-18 14:12
Yes, but same code is working fine with other accounts. It is only causing issue with one account. Also the   video I am uploading is same.

**Comment by mgp25** [comment] 2017-01-21 10:10
@jonnymike can you check what i told you? Does the `null` values appear in your other accounts, or does it only happen in one account.

**Comment by romalytvynenko** [comment] 2017-01-21 11:55
@mgp25 
I have the same issue as @jonnymike have. 
And for me `null` appears at all accounts when publishing video. And that's okay. Video publishing working well with `null`.

**Comment by samdonato** [comment] 2017-01-29 02:33
I'd also like to chime in here.  I opened two separate issues on this before and never had a resolution.  I have ffmpeg installed and verified it is working.  I also hard coded the sizes, specified a separate preview image.  I literally spent days trying to get this to work.  Transcode timeout sill happens all the time.

**Comment by mgp25** [comment] 2017-01-29 10:36
Can any of you try this settings on the video you are trying to upload?

- Video must be at least 3 seconds long
- Maximum width 1080 pixels 
- Frame Rate 29.96 frames per second
- H.264 codec / MP4
- AAC audio codec at 44.1 kHz mono
- 5,500 kbps video bitrate
- Less than 50 MBytes

**Comment by romalytvynenko** [comment] 2017-01-29 10:52
@mgp25 problem occurred not with special video but with account. I can upload video in "account1" but receive "Transcode Timeout" on the same video while uploading in "account2"

**Comment by mgp25** [comment] 2017-01-29 10:54
@romalytvynenko have you tested the above settings?

**Comment by romalytvynenko** [comment] 2017-01-29 10:57
@mgp25 no, I haven't. But I'll test it now. One moment, I'll find video. Maybe you have direct link for those one?

**Comment by romalytvynenko** [comment] 2017-01-29 11:17
@mgp25 just tried. As I said before, I can upload video video to account1, but cannot to account2. I must specify that video uploading to account2 (that fails) via proxy.

**Comment by mgp25** [comment] 2017-01-29 11:25
@romalytvynenko and have you tried without using proxy?

**Comment by romalytvynenko** [comment] 2017-01-29 11:26
Yes. From my home's IP everything working fine.

**Comment by mgp25** [comment] 2017-01-29 11:27
@romalytvynenko the conclusion then is that API works and Instagram doesnt like proxies, right?

**Comment by romalytvynenko** [comment] 2017-01-29 11:29
@mgp25 yes, I think so. But for account1 video upload works fine even with proxy.

**Comment by mgp25** [comment] 2017-01-29 11:30
@romalytvynenko but the only scenario it doesnt work, its using a proxy. I really dont know why that happens, but if the issue is using a proxy, the simplest solutions comes from not using a proxy only during video upload

Regards

**Comment by romalytvynenko** [comment] 2017-01-29 11:39
@mgp25 Thank you, I've got it. Forget to mention that upload video via proxy fails on `/media/configure`, but upload photo via proxy working fine.

**Comment by mgp25** [comment] 2017-02-01 10:24
Im going to close this issue, but ill continue researching about this. If any of you comes with a solution, just let me know and ill add it.

As for now, it seems using proxy might cause trouble uploading/configuring video, with the following response:

```json
{"crop_original_size":[null,null],"crop_center":[0,0],"crop_zoom":1},"extra":{"source_width":null,"source_height":null}}
← 202 	 50B
RESPONSE: {"status": "fail", "message": "Transcode timeout"}
InstagramAPI\ConfigureResponse : Transcode timeout
```

**Closed by mgp25** 2017-02-01 10:24 UTC

**Comment by romalytvynenko** [comment] 2017-02-01 10:42
@mgp25 
I don't think problem is there. Because `null` there even without proxy and everything uploading fine. I should specify, that photo uploads successfully via proxy to account2, but video is not.

I can give you login, password and proxy which I'm using, so you'll be able to reproduce error.

**Comment by mgp25** [comment] 2017-02-01 10:45
@romalytvynenko i know issue is only with video using proxy (no matter if there is a null or not). The fact that using proxy when configuring video is the main issue.

I dont use proxy so... It works always for me

**Comment by samdonato** [comment] 2017-02-01 15:34
@mgp25 what do you mean by proxy? I have seen there is new proxy functionality in the API, or are you referring to a server level proxy? I don't implement either.  I am hosted on Amazon EC2 and as far as I can tell, I go straight to instagram with my calls. This is a weird one.  Video uploads work 50% of the time for me. I can't predict why one video fails over the other.

**Comment by romalytvynenko** [comment] 2017-02-03 19:24
@mgp25 Hello!

I think I found problem's root. I've noticed that "Transcode timeout" error only happens when video uploading chunks respond with something like this:
`0-1999/6000`
`2000-3999/6000`
And last response is:
`4000-5999/6000`
So it's look like Instagram do not recognize that this is same job. So instead 
`{
     "result": "deprecated", "status": "ok", "configure_delay_ms": "6500"
}
` I get that piece of bytes.

And to confirm that `media/configure` will be okay if chunks upload will be successful I've try to upload one chunk at a time. And it worked!

So maybe you have ideas how to show Instagram that this is the same upload job?

Thank you!

**Comment by Triden** [comment] 2017-02-14 10:41
It may be a problem somewhere here?
  $ Request_size = floor (strlen ($ videoData) / 4);

You may not need to be round and divided by this number. At that evenly divisible. Although there may be a problem. Better to just send portions of subtraction, not division.

???

**Comment by Triden** [comment] 2017-02-14 10:57
Может я что еще путаю. Тут всегда вычитается информация. Даже в последнем блоке. Длина отправляется без учета.

  'Content-Length: '.($end - $start),
   'Content-Range: '.'bytes '.$start.'-'.($end - 1).'/'.strlen($videoData),

**Comment by Triden** [comment] 2017-02-14 11:49
@romalytvynenko Can I contact you then? I want to ask you a few questions.

**Comment by Triden** [comment] 2017-02-14 12:07
I also have one unit all posted.
