### ISSUE TITLE
Error : Something went wrong: Upload of "XXX.tmp" failed: All configuration retries have failed. 

### ISSUE THREAD

**Issue by rubberfashion** [mgp25/Instagram-API#2985] opened 2019-11-02 15:21 UTC
The following error occured:

Something went wrong: Upload of "INS36D.tmp" failed: All configuration retries have failed. Last error: InstagramAPI\Exception\BadRequestException: InstagramAPI\Response\ConfigureResponse: Upload id is None. in C:\xampp\htdocs\Insta\src\Exception\ServerMessageThrower.php:190
Stack trace:
#0 C:\xampp\htdocs\Insta\src\Client.php(586): InstagramAPI\Exception\ServerMessageThrower::autoThrow('InstagramAPI\\Re...', 'upload_id is No...', Object(InstagramAPI\Response\ConfigureResponse), Object(GuzzleHttp\Psr7\Response))
#1 C:\xampp\htdocs\Insta\src\Request.php(834): InstagramAPI\Client->mapServerResponse(Object(InstagramAPI\Response\ConfigureResponse), '{"message": "up...', Object(GuzzleHttp\Psr7\Response))
#2 C:\xampp\htdocs\Insta\src\Request\Internal.php(859): InstagramAPI\Request->getResponse(Object(InstagramAPI\Response\ConfigureResponse))
#3 C:\xampp\htdocs\Insta\src\Request\Internal.php(512): InstagramAPI\Request\Internal->configureSingleVideo(1, Object(InstagramAPI\Request\Metadata\Internal), Array)
#4 C:\xampp\htdocs\Insta\src\Request\Internal.php(1563): InstagramAPI\Request\Internal->InstagramAPI\Request\{closure}()
#5 C:\xampp\htdocs\Insta\src\Request\Internal.php(513): InstagramAPI\Request\Internal->configureWithRetries(Object(Closure))
#6 C:\xampp\htdocs\Insta\src\Request\Timeline.php(59): InstagramAPI\Request\Internal->uploadSingleVideo(1, 'C:\\Users\\dave\\A...', Object(InstagramAPI\Request\Metadata\Internal), Array)
#7 C:\xampp\htdocs\Insta\examples\uploadVideo.php(47): InstagramAPI\Request\Timeline->uploadVideo('C:\\Users\\dave\\A...', Array)
#8 {main}

**Comment by JRoy** [comment] 2019-11-02 16:19
Duplicate of #2972

**Comment by JRoy** [comment] 2019-11-02 16:20
Also, don't ask for support when you're using unsupported web usage

**Closed by JRoy** 2019-11-02 16:19 UTC
Labels: bug
