### ISSUE TITLE
400 58B RESPONSE: Something is wrong.

### ISSUE THREAD

**Issue by martsdev** [mgp25/Instagram-API#3067] opened 2019-12-17 07:17 UTC
# Bug Report

When I call the uploadPhoto.php script, I get this error:

> POST: https://i.instagram.com/api/v1/upload/photo/ → 177.31kB ← 400 58B RESPONSE: Something is wrong. Please check your input and try again. Something went wrong: Invalid request options.

Code is same as from examples.

I turned on debugs but **I dont get any debugs**. Only this error. I already looked at all closed issues, but I haven’t found a solution anywhere. All authorization details are correct.

I checked on the latest dev-master version, the problem is the same.

**Comment by schmidfelix** [comment] 2019-12-17 13:20
+1

**Comment by JRoy** [comment] 2019-12-17 15:59
Duplicate of #2972

**Closed by JRoy** 2019-12-17 15:59 UTC
Labels: bug

**Comment by foundVanting** [comment] 2019-12-18 01:26
+1

**Comment by martsdev** [comment] 2019-12-18 09:54
@JRoy so how we can solve the problem? On your link i haven't seen a solution

**Comment by heitorsampaio** [comment] 2019-12-19 14:13
Hey folks, I found a solution...

Go to the Instagram-API/src/Request and open the Internal.php go to line 101 and change:

$this->uploadPhotoData($targetFeed, $internalMetadata);

TO

$this->_uploadResumablePhoto($targetFeed, $internalMetadata);
