### ISSUE TITLE
Pagination in getFollowers/getFollowing not advancing

### ISSUE THREAD

**Issue by farhanansari** [mgp25/Instagram-API#1340] opened 2017-06-17 21:01 UTC
**** Just wanted to inform ****

- I have confirmed this in my old v1, current and dev-master version.
       
 $response = $ig->people->getFollowers($userid, $maxId);

Result count maxes out at 7345 and $maxId = $response->getNextMaxId(); is always null so obviously it won't advance.

I doubt if its a bug in the API code as I know it used to work before.  Perhaps IG has changed something on their end, if so, please do update the README.  If its something I'm doing wrong, I do apologize in advance :)

**Comment by SteveJobzniak** [comment] 2017-06-17 21:14
@farhanansari Thanks for reporting, but I think it's a duplicate of this? Please compare if this sounds familiar:

https://github.com/mgp25/Instagram-API/issues/1103

As we have seen, Instagram's maxId value can contain NULL, or numbers like "200", "400", or maxId tokens like "KEEA4N8OqM2rQhQoXg".

But @mgp25 may confirm if getFollowers still sends the correct params to their server. It could be that too.

**Comment by farhanansari** [comment] 2017-06-17 21:31
Close but not the same.  I am able to reproduce (no $maxId) every time on all versions.  This started yesterday mid day (PST), so I know its new.  #1103 is similar but I think what I have mentioned is brand new and different.

Btw: I get same result for getSelfFollowing(...).  Again, I don't think its the API but something to do with IG.  I'm sure you guys will be bombarded with questions.  Just try this on your end and see what you get.  I look forward to seeing result from your end.


//------------------ALTERED CODE FROM EXAMPLE--------------------------
$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);

try {
    $ig->setUser($username, $password);
    $ig->login();
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}

// Lets get Nike millions of users
$info = $ig->people->getInfoByName('nike');

try {
    $followings = [];

    // Starting at "null" means starting at the first page.
    $maxId = null;
    do {

        // Request the page corresponding to maxId.
        $response = $ig->people->getFollowers($info->user->pk, $maxId);
        echo "Count: " . count($response->getUsers()) . "\n";

        $maxId = $response->getNextMaxId();
        echo "Max: $maxId\n\n";

        // Dumping $response...
        print_r($response);

    } while ($maxId !== null); // Must use "!==" for comparison instead of "!=".

} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
}

// -------------------- ALTERED RESULT BELOW -------------------
Count: 7445
Max:

InstagramAPI\Response\FollowerAndFollowingResponse Object
(
    [users] => Array
        (
            [0] => InstagramAPI\Response\Model\User Object
   (
***********
                    [7443] => stdClass Object
                        (
                            [pk] => 1906689302
                            [username] => shabdenov.a
                            [full_name] => Арман
                            [is_private] =>
                            [profile_pic_url] => http://scontent.cdninstagram.com/t51.2885-19/s150x150/19051569_1702884570007018_4263384232514027520_a.jpg
                            [profile_pic_id] => 1536389874985559085_1906689302
                            [is_verified] =>
                            [has_anonymous_profile_picture] =>
                        )

                    [7444] => stdClass Object
                        (
                            [pk] => 5614392868
                            [username] => ngoc_thanh_phong
                            [full_name] => ngoc thanh phong
                            [is_private] =>
                            [profile_pic_url] => http://scontent.cdninstagram.com/t51.2885-19/s150x150/19227443_713209332197364_6471989134901641216_a.jpg
                            [profile_pic_id] => 1539376290662343511_5614392868
                            [is_verified] =>
                            [has_anonymous_profile_picture] =>
                        )

                )

            [big_list] =>
            [page_size] => 200
            [status] => ok
        )

**Comment by SteveJobzniak** [comment] 2017-06-17 21:32
I just tested getFollowers and getFollowing on a user I know, and its result was NULL next_max_id for both. In fact, the server itself had NO "max_id" value in the JSON blob it returned. So I would guess Instagram has finally fixed their APIs to prevent pagination attempts of other people's follower/following lists, and now only returns 1 page of followers/followings when looking at other people. Because in the past, it was always troublesome to get more than 1 page. Lots of endless loops etc as you can see above in closed tickets. Even the official app could get endless loops. So they may simply have fixed that now by removing the max_id token completely, to prevent pagination.

**Comment by farhanansari** [comment] 2017-06-17 21:34
Ah... so what would you suggest if one wanted to capture all followers of another user?  out of luck?

**Comment by SteveJobzniak** [comment] 2017-06-17 21:44
@farhanansari It was always very hard, and you needed luck (the server needed to return a working `next_max_id` which it often didn't do). Now they may have closed that possibility completely.

Perhaps because no normal people scrolled through 10,000 user long lists... I bet only spammers and weird bots tried to grab the whole lists. ;P

Instead, Instagram recently added the "query" param feature (which we have implemented), which returns a list of users matching the search query. All our functions take that $searchQuery param and you can use it to find people in their user lists.

**Comment by SteveJobzniak** [comment] 2017-06-17 21:48
@farhanansari By the way I noticed a bug in your pasted code. You're putting $maxId in param number two, which is the $searchQuery param. $maxId is the third param.

**Comment by azureatlas** [comment] 2017-06-17 21:54
@SteveJobzniak the query param seems to only return results within those 7,500 or so limited results, so effectively it isn't providing any value, as of now (you could filter on the client and get the same results). By the way, the new limit doesn't just affect getting all followers of other users, but also your own. There are tons of legitimate uses for getting the full list of your own followers... I hope this limitation gets solved somehow soon.

**Comment by SteveJobzniak** [comment] 2017-06-17 21:59
@farhanansari Just for completeness, I tried `getSelfFollowing()` on my account (which follows 423 people). Not even that function can get any `next_max_id` value. So even when querying your own account, you will only get a list of 200.

@azureatlas Oh wow that's nuts, now I see what they've done! Holy sh... Disregard all my previous comments (including what I just wrote to farhan above). It turns out that Instagram has gotten rid of next_max_id completely from getFollowers/getFollowing. They now return up to a few thousand results in a single query. That's pretty dumb. Big waste of data.

Well, I'll update all functions to remove maxId param from followers/following and from the pagination code example we have... Thanks all for discovering that Instagram no longer uses pagination for followers/following...

**Comment by farhanansari** [comment] 2017-06-17 22:00
@azureatlas I agree.  I on many occasions go through full list of followers.  I was just coding to test new Query feature, I guess it will be a dead end per your comment.   Could this be a bug (i'm hoping)  

I am open for work arounds suggestions.

**Comment by SteveJobzniak** [comment] 2017-06-17 22:00
No it's not a bug. Instagram has changed the API. No more pagination.

**Comment by azureatlas** [comment] 2017-06-17 22:03
There are a couple of things in the reply that look strange however:
1) even when you get 7,500 followers back, the JSON says "page_size": 200
2) The "big_list": false in the response JSON makes me wonder...

**Comment by SteveJobzniak** [comment] 2017-06-17 22:04
@azureatlas Yep but since there is no "next_max_id" param in the JSON they give us it doesn't matter.

**Comment by mgp25** [comment] 2017-06-17 22:04
As @SteveJobzniak said, Instagram server has changed the response, not it only will show some thousands of followers or less. Thats it, no API issue, just an Instagram update in their API response. Change was introduced yesterday.

Have a nice weekend

Regards

**Comment by farhanansari** [comment] 2017-06-17 22:10
Shocker!!! Thats what I had initially suspected.  Today they are returning few thousands, tomorrow it might be reduced to few hundreds.  I might as well shut down my server now and have a full night sleep :)
 
If anyone come up with any suggestions, please do update me. 

Thanks for the help @SteveJobzniak @azureatlas and @mgp25

**Comment by SteveJobzniak** [comment] 2017-06-17 22:17
@farhanansari Thank you too. I am very grateful that you took the time to report this. I hadn't noticed this change at all (since me and mgp don't use those functions personally) and the bug would have remained a long time after 3.0 has been released, if you hadn't reported it. ;)

We're now up-to-date with this change:
https://github.com/mgp25/Instagram-API/commit/bf2d103078dc94555e8ab1deb3a5cee454be43fb

And yeah I don't think Instagram liked people who paginated those endpoints. They prefer less API queries. Almost their entire platform sends megabytes of data pointlessly just IN CASE you want it, simply to avoid extra database queries. Because bandwidth is cheaper than database queries, on such a popular site. Lots of database queries slows down the entire site.

**Comment by Javanshir** [comment] 2017-06-19 08:45
Seems to work again... 
The responses are like before, 200 at a time with pagination

**Comment by ranjbarhadi** [comment] 2017-06-19 09:01
@mgp25 @SteveJobzniak it seems pagination is working again. it was a temporary change

**Comment by farhanansari** [comment] 2017-06-19 11:47
@mgp25 @SteveJobzniak Yup, I confirm.  It works again.

**Comment by SteveJobzniak** [comment] 2017-06-19 21:09
@farhanansari @Javanshir @ranjbarhadi Okay so the code changes we made have been reverted for now. Please let us know if Instagram changes this again. They may intend to bring the change back again at a later time.

**Comment by SteveJobzniak** [comment] 2017-06-22 21:39
@farhanansari @Javanshir @ranjbarhadi @mgp25 It seems like Instagram has yet again removed next_max_id and is dumping all followers/followings in a single query. I tried with `dev-master` (10.15.0 client) and the server is not sending any next_max_id, and has all users in a single reply.

@mgp25 Before we re-add the code changes I made earlier, let's wait a while to see what happens. Instagram may be going back and forth.

**Comment by mgp25** [comment] 2017-06-22 21:43
@SteveJobzniak instagram is testing some new features so it may change from time to time. Lets wait a couple versions (like a week) and see how is evolving, and depending on that we'll see.

**Comment by SteveJobzniak** [comment] 2017-06-22 21:48
@mgp25 Yeah I suspect the same. Sounds good to me.

**Comment by ranjbarhadi** [comment] 2017-06-23 03:07
I'm receiving 200 user per request and a next_max_id token each time. I have spoken with my friends. I think this time the change is not global because we didn't experience it.

**Comment by SteveJobzniak** [comment] 2017-06-23 09:22
@ranjbarhadi I noticed that it seems to depend on the user.

When I use "getFollowing" on a user with ~390 followings, I get them all at once, and I get no "next_max_id" field in the response.

When I use "getFollowers" on Nike, I get 200 per page:

```php
    $id = $ig->people->getInfoByName('nike')->getUser()->getPk();
    $res = $ig->people->getFollowers($id);
    var_dump($res);
    var_dump($res->getFullResponse()->next_max_id);
```

**Comment by ranjbarhadi** [comment] 2017-06-23 09:33
@SteveJobzniak I've checked once on an account with more than 70k followers and on a an account with 700 followers. i still get 200 users every time and pagination is working. but if what you are saying is happening it's gonna be awesome since it makes more sense to receive all followers and following in a blob when a user have a few followers/following. i will keep checking in my end and notify you if anything happens. cheers

**Comment by SteveJobzniak** [comment] 2017-06-23 10:35
@ranjbarhadi Thanks for the extra info! So far we know 700+ definitely paginates. And ~380 or less does not paginate.

**Comment by brenovieira** [comment] 2017-06-25 04:50
Just to add my usecase: +11followers, +2k followings

I've noticed `getFollowers` and `getFollowing` were not paginating last week and were returning up to ~7.500 and then they returned to paginate.

But since few days ago, `getFollowing` is retrieving the whole ~3k followings at once (not paginating) and `getFollowers` is paginating again 200 per call.

BTW: I'm using the `v2.0` release version right now, but I'll probably move to `master` tomorrow.

**Comment by SteveJobzniak** [comment] 2017-06-25 06:38
@brenovieira Thanks for that information. So you get a mix of paginating and not. It's hard to guess what Instagram is doing. We must wait and see...

**Comment by ranjbarhadi** [comment] 2017-06-25 07:10
@brenovieira thanks for the information. I didn't notice the change on the following endpoint. did you check if the following endpoint paginates for users with more than `10k` following? and to be more precise can we in every circumstance get all of the people we are following no matter how much following we have?

**Comment by Yahixi** [comment] 2017-06-25 13:08
Hello,

Since a few days ago the pagination of the function getUserFollowings is not working, it returns all the following users of the account. This problem arised since the other pagination problems appear. How could I fix it? Any solution?

Thanks!

**Comment by mgp25** [comment] 2017-06-25 13:10
@Yahixi please read the full issue. Here its explained

**Comment by LauR2** [comment] 2017-06-25 13:34
@mgp25 Thanks! I read this issue but thought that was different in getUserFollowings function, sorry. I'll follow this topic to solved this when a solution appears. Congrats for your work! It's a very useful API

**Comment by brenovieira** [comment] 2017-06-25 22:55
@SteveJobzniak exactly.

@ranjbarhadi, I don't see how it would be possible, since every ig account is limited to up to ~7.500 followings anyway. But in any case, I didn't check.. I just run this library for the same account, which has ~11k followers and ~3k followings.

One question:
- Which order functions `getFollowers` and/or `getFollowings` return the users?

I mean, Instagram returns users ordered by their date creation, id, relationship date with the given user, ...?

**Comment by mgp25** [comment] 2017-06-27 09:25
@brenovieira ansquering to your question: relationship date with the given user.

@SteveJobzniak i think we should keep pagination. And this issue is already done. Probably in some cases it wont paginate and it will in others. So far, i get pagination in all users.

**Comment by SteveJobzniak** [comment] 2017-06-27 09:28
@mgp25 Yeah it seems like pagination will still exist in most cases. We can close this and keep pagination code. :)

**Closed by SteveJobzniak** 2017-06-27 09:28 UTC
Labels: Researching

**Comment by SteveJobzniak** [comment] 2017-06-27 09:31
Oh and most likely they made a mistake in their server code when they returned 7500 users per query. It was quickly fixed by them in a day or so, so I don't think they will remove pagination completely again. It makes no sense to dump so much data over the network since most people don't even scroll the follower-following list.

**Comment by SteveJobzniak** [comment] 2017-06-29 18:30
They seem to have settled now, so for completeness this is their behavior:

getFollowing on a user with 388 followings gives 388 at once.

getFollowing on a user with a few thousand followings gives 200 at once.

So it paginates dynamically if a user has something like >= 400 followers/followings.

**Comment by Lsleiman** [comment] 2017-07-17 16:08
Seems like max_id and pagination is removed from all getFolllowers, regardless of the account size...

**Comment by mgp25** [comment] 2017-07-17 16:43
Not true, its still used. Instagram sometimes do experiments and doesnt appear, but its still active

**Comment by Lsleiman** [comment] 2017-07-18 08:23
> $maxId = $response->getNextMaxId();
> echo "Max: $maxId\n\n";

working on media feed but not on following feed... just tested.
