### ISSUE TITLE
Highlight Exceptions

### ISSUE THREAD

**Issue by tobiasmanroth** [mgp25/Instagram-API#2560] opened 2019-03-13 09:58 UTC
### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

When trying to create a highlight with this code:

```php
$ig = createInstagramClient($command_params);
login($ig, $username, $password);

$addMedia = ["1984092565558742664_6985928300"];
$response = $ig->highlight->create($addMedia, $title = 'TEST', $coverMediaId = null, $module = 'self_profile');
```

Following error message is thrown:

`No response from server. Either a connection or configuration error.","class":"InstagramAPI\\Exception\\EmptyResponseException`

Here is the debug log:
```
DATA: signed_body=a5ec44915c4gasgdcdc2064f1fag15ec455573807be47j5ghgh2854c9f72.{"supported_capabilities_new":"[{\"name\":\"SUPPORTED_SDK_VERSIONS\",\"value\":\"13.0,14.0,15.0,16.0,17.0,18.0,19.0,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0,40.0,41.0,42.0,43.0,44.0,45.0,46.0,47.0,48.0,49.0,50.0,51.0,52.0,53.0\"},{\"name\":\"FACE_TRACKER_VERSION\",\"value\":\"12\"},{\"name\":\"segmentation\",\"value\":\"segmentation_enabled\"},{\"name\":\"WORLD_TRACKER\",\"value\":\"WORLD_TRACKER_ENABLED\"}]","source":"self_profile","creation_id":"1552469688036","_csrftoken":"e3rJ1oa2hAMH1qvTQiYTKQMQBTDjQzRi","_uid":"6985928300","_uuid":"4fa34c52-905e-4371-bda3-172971487a5b","cover":"{\"media_id\":\"1984092565558742664_6985928300\",\"crop_rect\":\"[0.0,0.19545822,1.0,0.8037307]\"}","title":"TEST","media_ids":"[\"1984092565558742664_6985928300\"]"}&ig_sig_key_version=4
← 500    25B
RESPONSE: Oops, an error occurred.
```

## Describe your issue ##

The highlight is created but an error is thrown.

I already found these past solved issues:
https://github.com/mgp25/Instagram-API/issues/2326
and this one:
https://github.com/mgp25/Instagram-API/issues/2153

**Comment by JRoy** [comment] 2019-03-13 15:42
Parameters probably changed, will look into it

**Comment by JRoy** [comment] 2019-03-13 19:13
Update: Instagram Services seem to be down, this is probably an issue with that. Will keep this open until certain, however.

**Comment by tobiasmanroth** [comment] 2019-03-13 20:18
Thank you! I'm pretty sure that the Instagram issues started later this day because I was testing other parts of this API which worked just fine

**Comment by tobiasmanroth** [comment] 2019-03-14 08:50
Although Instagram is working again, I get the same error when creating a highlight. The highlight is created on Instagram though.

**Comment by szokeptr** [comment] 2019-03-14 08:52
The problem is that the `crop_rect` parameter shouldn't be hard-coded in this library. Playing with those values gets a successful response.

**Comment by tobiasmanroth** [comment] 2019-03-14 08:53
Thank you so much, I'll try that

**Comment by tobiasmanroth** [comment] 2019-03-14 16:18
Update: When I remove the "crop_rect" entry completely it works just fine. Instagram creates the crop on it's own

**Comment by JRoy** [comment] 2019-03-14 18:32
While this does appear that it could have been an issue with Instagram's servers, I just looked at the code and am aware that this endpoint may need updating.

Reopening.

**Comment by JRoy** [comment] 2019-03-15 01:11
Fixed in #2568

Waiting for code review/merge and then I'll close this

**Comment by tobiasmanroth** [comment] 2019-03-15 06:50
Thank you for this swift bug fix!

**Closed** 2019-03-15 19:06 UTC
Labels: Fixed, bug

**Comment by JRoy** [comment] 2019-03-15 19:08
Endpoints have been updated in 05676aa

Cheers.
