### ISSUE TITLE
UploadPhoto problem

### ISSUE THREAD

**Issue by capslog** [mgp25/Instagram-API#2756] opened 2019-07-10 14:30 UTC
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [ ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ ] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [ ] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [ ] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [ ] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

Description of problem:
A few days ago, de UploadPhoto function is working, but the 8 of july for foward stop work the caption, the media is sended but the caption not.
I run composer update for update dependencies but problem continue...

```json response

← 200 	 1.28kB
--
  | RESPONSE: {"media": {"taken_at": 1562766409, "pk": 2084958220730094047, "id": "2084958220730094047_11354216550", "device_timestamp": 222409121030325, "media_type": 1, "code": "BzvQnSGJdHf", "client_cache_key": "MjA4NDk1ODIyMDczMDA5NDA0Nw==.2", "filter_type": 0, "image_versions2": {"candidates": [{"width": 1080, "height": 1080, "url": "https://scontent-lga3-1.cdninstagram.com/vp/c1c52d9519d44a51543e05fc8f9d0261/5DC44808/t51.2885-15/e35/66620428_2044716348966739_5599518527186508870_n.jpg?_nc_ht=scontent-lga3-1.cdninstagram.com\u0026_nc_cat=107\u0026se=7\u0026ig_cache_key=MjA4NDk1ODIyMDczMDA5NDA0Nw%3D%3D.2", "estimated_scans_sizes": [14459, 28918, 43377, 57836, 72295, 87260, 105635, 117642, 130131]}, {"width": 480, "height": 480, "url": "https://scontent-lga3-1.cdninstagram.com/vp/71d001e960080fd7aec66382a62d1ac9/5DB98208/t51.2885-15/e35/s480x480/66620428_2044716348966739_5599518527186508870_n.jpg?_nc_ht=scontent-lga3-1.cdninstagram.com\u0026_nc_cat=107\u0026ig_cache_key=MjA4NDk1ODIyMDczMDA5NDA0Nw%3D%3D.2", "estimated_scans_sizes": [5069, 10138, 15207, 20276, 25345, 31639, 408627, 45622, 45622]}]}, "original_width": 1080, "original_height": 1080, "user": {"pk": 11354216550, "username": "momentomistico.oficial", "full_name": "Momento M\u00edstico", "is_private": false, "profile_pic_url": "https://scontent-lga3-1.cdninstagram.com/vp/0cada36bfd2dd1a107814fb8f9e91b86/5DB02CFC/t51.2885-19/s150x150/53822842_486493868553742_8515171237285068800_n.jpg?_nc_ht=scontent-lga3-1.cdninstagram.com", "profile_pic_id": "2003998902026958256_11354216550", "has_anonymous_profile_picture": false, "can_boost_post": true, "can_see_organic_insights": true, "show_insights_terms": false, "reel_auto_archive": "on", "is_unpublished": false, "allowed_commenter_type": "any"}, "can_viewer_reshare": true, "caption_is_edited": false, "comment_likes_enabled": false, "comment_threading_enabled": false, "has_more_comments": false, "max_num_visible_preview_comments": 2, "preview_comments": [], "can_view_more_preview_comments": false, "comment_count": 0, "boosted_status": "not_boosted", "photo_of_you": false, "caption": null, "fb_user_tags": {"in": []}, "can_viewer_save": true, "organic_tracking_token": "eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjp0cnVlLCJ1dWlkIjoiOGYwMWRlOGYyNWI0NDY2ZGFmYWVhOTFhNDI4ZDk3NWEyMDg0OTU4MjIwNzMwMDk0MDQ3Iiwic2VydmVyX3Rva2VuIjoiMTU2Mjc2NjQxMjM2NHwyMDg0OTU4MjIwNzMwMDk0MDQ3fDExMzU0MjE2NTUwfDA1NjVkN2FmMGFmZjM1NjZiYmJkODlmZWVmOWE2NjhjYjdjYmYzNmIxYmNmNWYyZjE2OTY4ZTNlMzhlZGRkOTYifSwic2lnbmF0dXJlIjoiIn0="}, "upload_id": "222409121030325", "status": "ok"}

**Comment by gurenovich** [comment] 2019-07-10 15:14
same problem

**Comment by JRoy** [comment] 2019-07-10 15:15
Duplicate of #2665

**Closed by JRoy** 2019-07-10 15:15 UTC
Labels: asshole, duplicate

**Comment by szokeptr** [comment] 2019-07-10 15:56
@JRoy this is **not** a duplicate of my issue.

**Comment by capslog** [comment] 2019-07-10 16:16
> @JRoy this is **not** a duplicate of my issue.

I'm trying to have some help ...

**Comment by JRoy** [comment] 2019-07-10 16:52
@szokeptr it is, Instagram is slowly starting to deprecate things on the old endpoint. Different error message, same root cause.
