### ISSUE TITLE
Uploading video : Uploaded image isn't in the right format.

### ISSUE THREAD

**Issue by GitforDev** [mgp25/Instagram-API#1102] opened 2017-03-19 21:38 UTC
Hello, mgp25.
First, thanks for your sources.

Now, I am facing an issue when trying to upload a video.
The video is what I have downloaded directly from Instagram.
But, when I try to upload it again, I see the following error.

------------------

> POST: upload/video/ DATA: --39416c40-efbc-435b-ac30-d2bb5535bf66 Content-Disposition: form-data; name="upload_id" 1489958847405 --39416c40-efbc-435b-ac30-d2bb5535bf66 Content-Disposition: form-data; name="_csrftoken" 9gTWQYGz5E9QEtw5BoWpTfRzKlmRJZL0 --39416c40-efbc-435b-ac30-d2bb5535bf66 Content-Disposition: form-data; name="media_type" 2 --39416c40-efbc-435b-ac30-d2bb5535bf66 Content-Disposition: form-data; name="_uuid" 39416c40-efbc-435b-ac30-d2bb5535bf66 --39416c40-efbc-435b-ac30-d2bb5535bf66-- ← 200 2.12kB RESPONSE: {"status": "ok", "upload_id": "1489958847405", "video_upload_urls": [{"url": "https://upload.instagram.com/api/v1/stage/video/?target=frc3c11\u0026vx_token=10014\u0026staging_in_tao=0", "expires": 1805318847.7265284, "job": "AQDWgUZY5yBPKTq1OkHeKkpADZNbIlphtIeeCz6U3bm164q1SMWJqaG-PD9Ltn-gdIUJd1qDZMmSIBhk9JUOhg0vCi7groPLHjG9-auYJ8oGZHWQiKpVNTZfBJyVgHwQ1-Q9oUPehEUAfm-awJ6nKnTKSdrih77sIeRxk3OQBijV-A2AXkh2BcuirCzDJ2cqX0hJdkxPmJ36PcOfZpz0cQhlTLlGzMm9hxsYQbw3_6PUrapxSaKu-We0Bzdy5Lm_RmcWitK2W3gsi6L4gDR0cP5AWj0TkWrUPWbl27KQCKadjqiFLnRm3mYWrvcVXnRVpwgV92McPvYIryhXLay-X5nW5aoqPI9cpqGhhQ6Xf448YA"}, {"url": "https://upload.instagram.com/api/v1/stage/video/?target=frc1c23\u0026vx_token=10004\u0026staging_in_tao=0", "expires": 1805318847.727291, "job": "AQA-ebR9A5OQmoJqLsYh0e3chPbV2QO3ZsJW1MSemehh5BAGnSwD_596tUvC6tgeIdEAWE17YoPCGGc-3cdEQfmLoOfPfqq7fuxVQPLrBvF7k8E1a39P-wIn-a7dRjYaUSz4kGTVsoNf7umznm5yOzQhi3ffyKNg40ys08jjhidI3eSldgTBigSqzvLrD_brJSAajxI7-BPOXh6QNW_jAFNrBR8cDnTkHB6caMclKoevfyMlMfYYTwVaiyCq4hdlJOImPuGzQVRD8S2Gp02OGOlGi5_6LWmEUMqC_Lu9wlPieZpSIm8JEYj3EV2uhHSJQGem8FgipHTwzCF-V656sPL_9zod5UW9iPWYzh1gFtH8IQ"}, {"url": "https://upload.instagram.com/api/v1/stage/video/?target=frc3c11\u0026vx_token=10001\u0026staging_in_tao=0", "expires": 1805318847.7280824, "job": "AQAxgcVFHRYwAMBjEHGxq5_3eIuw0GCmQAhZqBZWlIJ5lqoaltOdrrLcDhNw_Xl9TnfzrzDhX-W4IjjD_BUmI8nuNI8EYZ8JeLXQzU0yJnaee__rndHyK5byF7u1R3HVALhE24IPqK730lvDX3yjbrXdV5ufoWNIWpeRgMA9aGVAs3E0W6qyt_g0ykS0cEXggf5ROZhxqVPRuMHdUjcIrrlVobQ02deXwcODxEQ26VvQMZPCtK2DZzTs6iwgUSG9NAfnDRUFL5bX_cvg8BQXFzLt_RSdaAdFNyDaAzu5gGKBBUnS_hnjI9TeoqAtGxcQJaRGAF1QE5UgXcvyhuy0tgiq43IHdGMdcF9XXrh7ppz2pw"}, {"url": "https://upload.instagram.com/api/v1/stage/video/?target=frc1c23\u0026vx_token=10007\u0026staging_in_tao=0", "expires": 1805318847.7288635, "job": "AQC3dylO_GvODPUZgIWNex0-WKl91wauQCcaom2qGbFPaMCB15w1-Ug230DOe4UM9eJz0yJmtJ4PRfO0x-7br7zDAyRVc69grvtx5Y8XiASBGNjc6vq4I521ENksth8AY0RRnPj5d1gccuTtAtQ98U8waDap7-PfuPGjREXf37a5gx9X01xnd5Yzm-qA9vYK2Jz9X6jaFqHEdNnXqOcW6afWNJ6pWbQk2At88ZwN14hT47YL93gOw9QUnMLH8aHFlyFojtDFNs-EdC_MI3fUbHEWd0UnOM24Xb3mdScrHg8e6ntvQKgCl4dEcSHOz5cFFFGuKjnCU0UdC7V7m_d9z5-KZ7ybNf__ymZsGzsZuoy0zQ"}]} POST: https://upload.instagram.com/api/v1/stage/video/?target=frc1c23&vx_token=10007&staging_in_tao=0 → 483.16kB ← 201 16B RESPONSE: 0-494757/1979032 POST: https://upload.instagram.com/api/v1/stage/video/?target=frc1c23&vx_token=10007&staging_in_tao=0 → 483.16kB ← 201 16B RESPONSE: 0-989515/1979032 POST: https://upload.instagram.com/api/v1/stage/video/?target=frc1c23&vx_token=10007&staging_in_tao=0 → 483.16kB ← 201 17B RESPONSE: 0-1484273/1979032 POST: https://upload.instagram.com/api/v1/stage/video/?target=frc1c23&vx_token=10007&staging_in_tao=0 → 483.16kB ← 200 70B RESPONSE: {"status": "ok", "configure_delay_ms": "6500", "result": "deprecated"} POST: upload/photo/ → 765B ← 200 46B RESPONSE: {"status": "ok", "upload_id": "1489958847405"} POST: media/configure/?video=1 DATA: ig_sig_key_version=4&signed_body=9265a1bba868e8416cc4ae966ab230b80b9c8b1fd5296aa9206124674b17fdde.{"configure_mode":1,"video_result":"deprecated","upload_id":"1489958847405","source_type":4,"length":0,"date_time_original":1489958853,"filter_type":0,"device":{"manufacturer":"LGE","model":"RS988","android_version":"23","android_release":"6.0.1"},"_csrftoken":"9gTWQYGz5E9QEtw5BoWpTfRzKlmRJZL0","_uuid":"39416c40-efbc-435b-ac30-d2bb5535bf66","_uid":"4853133402","caption":"Test Video"} ← 400 73B RESPONSE: {"status": "fail", "message": "Uploaded image isn't in the right format"} InstagramAPI\ConfigureVideoResponse: Uploaded image isn't in the right format.

------------------
I am stuck at this urgent issue, so please kindly help me.

Regards

**Comment by SteveJobzniak** [comment] 2017-03-19 21:52
"Uploaded image isn't in the right format" means the server is rejecting our uploaded video thumbnail.

That's strange. They should accept all thumbnail files regardless of photo dimensions. Because video rules are not the same as photo rules. Video thumbnails can be any dimension that a legal video can be, as far as I know.

@mgp25 If it turns out that we need to process video thumbnail images before we upload them, then the new ImageAutoResizer class will certainly let us do that, but it would take some careful thinking to integrate it.

@GitforDev What's the specification for your video file? Run this command: `ffprobe <the video file>` and show us the info that comes out, from the `Input #` line and forwards. It will show the formats, size of the video, etc.

ffprobe is a command from the ffmpeg package, which is a required dependency for uploading videos.

**Comment by mgp25** [comment] 2017-03-19 22:21
@SteveJobzniak In fact, the thumbnail is a photo and therefore should follow the same criteria as if we uploaded a regular photo

**Comment by SteveJobzniak** [comment] 2017-03-19 22:31
@mgp25 Okay, then the problem is that his video is not an allowed photo dimension, so our thumbnail is wrong. Let's talk on Skype.

**Comment by GitforDev** [comment] 2017-03-20 04:50
@mgp25 & @SteveJobzniak 
Thank you for your reply. 
I tested with the following video. 
https://www.dropbox.com/s/knwm3loqkwbjsjp/sample.mp4?dl=0

**Comment by GitforDev** [comment] 2017-03-20 04:56
And now I'm using php version 5.6.28 on apache web server(Xampp) windows 10. 
I'm not sure if this is helpful. :)

**Comment by SteveJobzniak** [comment] 2017-03-20 09:21
@GitforDev Thanks for the test file! I'm able to upload it with the nearly-finished version 2.x of the library (dev-master). Perhaps you are using the old 1.6 version of the library?

Either way I'll add some code to make sure that we always resize video thumbnails to conform to Instagram's rules. Even though that wasn't the issue in this ticket.

**Comment by SteveJobzniak** [comment] 2017-03-20 09:22
@GitforDev This is literally all I had to do, with the file you gave me:

```php
require __DIR__.'/vendor/autoload.php';

$ig = new \InstagramAPI\Instagram(true);
$ig->setUser(..., ...);
$ig->login();
$ig->uploadTimelineVideo('sample.mp4');
```

**Comment by GitforDev** [comment] 2017-03-20 09:26
@SteveJobzniak  I downloaded nearly-finished version 2.x(dev-master) using composer.

**Comment by SteveJobzniak** [comment] 2017-03-20 09:28
@GitforDev And it's not working for you? If so then it's a windows issue. Works fine on PHP7 with MacOS here. But either way I am going to add some better code for the thumbnail uploading soon, to ensure all thumbnail images follow Instagram's allowed specifications.

**Comment by GitforDev** [comment] 2017-03-20 09:29
@SteveJobzniak 
Yes. It's not working. 
It shows the above issue that I posted.

**Comment by GitforDev** [comment] 2017-03-20 09:30
@SteveJobzniak Now I'm using PHP5.6.28. Should I install PHP7 on windows 10 and test it?

**Comment by SteveJobzniak** [comment] 2017-03-20 10:39
@GitforDev Try again. I just committed _the_ fix 8 minutes ago. It's now running all thumbnails through our new automatic image processor which guarantees that it will fit Instagram's specifications.

https://github.com/mgp25/Instagram-API/commit/e520b335ee3693eef531b8cc3370aef59aef7556

**Comment by SteveJobzniak** [comment] 2017-03-20 12:41
@GitforDev Please let me know the results when you have time.

**Comment by GitforDev** [comment] 2017-03-20 15:29
@SteveJobzniak Thank you so much. I will test again let you know if it works. :)

**Comment by GitforDev** [comment] 2017-03-20 16:44
@SteveJobzniak I just tested it and it says as follows. 
"Something went wrong: You must have FFmpeg to generate video thumbnails."
So I followed this way to fix it but still it shows same error. 
http://ukphpdeveloper.blogspot.my/2012/08/how-to-install-ffmpeg-in-xampp.html

**Comment by mgp25** [comment] 2017-03-20 17:17
All fixes working fine, you need to install ffmpeg and the installation of that is not API issue, but you can find lots of good guides searching on google

Regards

**Closed by mgp25** 2017-03-20 17:17 UTC
Labels: Fixed

**Comment by GitforDev** [comment] 2017-03-20 18:07
Yeah! I installed ffmpeg and it worked! Thank you again for your source code and support!

**Comment by SteveJobzniak** [comment] 2017-03-20 19:19
@GitforDev Okay so your problem was that you didn't have FFmpeg.

When I made the thumbnail generation autoresize to follow Instagram specs, I also added some checks to warn if user lacks FFmpeg.

**Comment by GitforDev** [comment] 2017-03-20 19:22
@SteveJobzniak  Yes. it was the problem that I didn't have FFmpeg. Now it works perfect. 
Thank you.  :-)

**Comment by SteveJobzniak** [comment] 2017-03-20 19:33
@GitforDev Happy story with a happy ending. ;-)
