### ISSUE TITLE
Getting error "Invalid request options."

### ISSUE THREAD

**Issue by 1poyraz** [mgp25/Instagram-API#3019] opened 2019-11-20 13:07 UTC
Please help me. I was able to upload images before, but now I get "Invalid request options." Error.

Example Code:

```
<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);
set_time_limit(0);


require 'vendor/autoload.php';
\InstagramAPI\Instagram::$allowDangerousWebUsageAtMyOwnRisk = true;

$username= 'xxxx';
$password= 'xxxxx';

$ig = new \InstagramAPI\Instagram();
try{
	$ig->login($username, $password);
	
$photo = __DIR__ . '/1.jpeg';
$metadata = [
    'caption' => 'Bu fotoğraf API ile ders esnasında yüklendi <3'
];

$photo = new \InstagramAPI\Media\Photo\InstagramPhoto($photo);
echo $ig->timeline->uploadPhoto($photo->getFile(), $metadata);

}catch (\Exception $e){
	echo $e->getMessage();
}



?>
```

Problem, I searched for FAQs and wiki topics but couldn't find them.
I'd appreciate it if you helped.

**Comment by michelmelo** [comment] 2019-11-20 13:36
@1poyraz  is -> #2972

**Comment by michelmelo** [comment] 2019-11-20 13:36
Duplicate of #2972

**Comment by 1poyraz** [comment] 2019-11-20 14:10
@michelmelo  I Couldn't Find a Solution There

**Closed** 2019-11-20 14:33 UTC
Labels: duplicate

**Comment by moazam1** [comment] 2019-12-07 01:30
Having same issue.

**Comment by Otooo** [comment] 2019-12-07 16:48
I also having the same problem
