### ISSUE TITLE
Entity not found (PushReceiver.php not working)

### ISSUE THREAD

**Issue by hydefus** [mgp25/Instagram-API#2809] opened 2019-08-13 21:09 UTC
Running last version of this instagram-api I am getting the following error when logging into Instagram account.

It looks like if Instagram had changed something in its login process:

[2019-08-13 21:06:05] push.INFO: Publish flow has been completed. [] []
[2019-08-13 21:06:05] push.INFO: Existing keepalive timer has been canceled. [] []
[2019-08-13 21:06:05] push.INFO: Setting up keepalive timer to 900 seconds [] []
[2019-08-13 21:06:05] push.INFO: Existing keepalive timer has been canceled. [] []
[2019-08-13 21:06:05] push.INFO: Setting up keepalive timer to 900 seconds [] []
[2019-08-13 21:06:05] push.INFO: Received a message from topic "/fbns_reg_resp". ["{\"pkg_name\":\"com.instagram.android\",\"error\":\"The entity backed by id 464668660305394 was not found. This represents permanent unavailability. The ent was deleted or it never existed. (EntID: 464668660305394)\"}"] []
[!!!] Got fatal error from FBNS: The entity backed by id 464668660305394 was not found. This represents permanent unavailability. The ent was deleted or it never existed. (EntID: 464668660305394)
[2019-08-13 21:06:05] push.INFO: Stopping FBNS client... [] []
[2019-08-13 21:06:05] push.INFO: Disconnected from the broker. [] []
[2019-08-13 21:06:05] push.INFO: Network connection has been closed. [] []
[2019-08-13 21:06:05] push.INFO: Existing keepalive timer has been canceled. [] []

**Comment by christianoerick** [comment] 2019-08-13 21:42
I'm having the same problem. It started 1 hour ago !!! Push Notification doens't work!

**Comment by christianoerick** [comment] 2019-08-14 04:20
@hydefus is it working for you?

**Comment by usamaejaz** [comment] 2019-08-14 07:41
Same issue for me.

**Comment by JRoy** [comment] 2019-09-19 11:16
Duplicate of #2287

**Closed** 2019-09-19 11:16 UTC
Labels: duplicate
