### ISSUE TITLE
Curl  Error 6 maybe parsing error

### ISSUE THREAD

**Issue by ilkerbfl** [mgp25/Instagram-API#2395] opened 2018-12-25 18:32 UTC
POST:  https://b.i.instagram.com/api/v1/accounts/read_msisdn_header/
DATA: signed_body=6f64a1988acb1e29f9def143d83ad24761ec82019ea035138fcc41a73b26bb6b.{"mobile_subno_usage":"ig_select_app","device_id":"cb40d085-9753-4af6-b830-eaf60acd4be9"}&ig_sig_key_version=4
← 200 	 16B
RESPONSE: {"status": "ok"}

POST:  https://b.i.instagram.com/api/v1/qe/sync/
DATA: signed_body=1002db4a147db813c8d98f798168f350d1ec12a687177a8830aaba74b0329ffc.{"id":"cb40d085-9753-4af6-b830-eaf60acd4be9","experiments":"ig_growth_android_profile_pic_prefill_with_fb_pic_2,..... ****omitted**"}&ig_sig_key_version=4
← 200 	 1.61kB
RESPONSE: {"experiments": [{"name": "ig_android_background_voice_phone_confirmation_prefilled_phone_number_only",......****omitted**}

POST:  https://b.i.instagram.com/api/v1/launcher/sync/
DATA: signed_body=9c97c6e8ecab32aae9c387fa41c9ed285268981c9900012011852b52a11d5d6e.{"_csrftoken":"0YAq6HXZ22QkupeYI3EvqiXvefmO05Cu","id":"cb40d085-9753-4af6-b830-eaf60acd4be9","configs":""}&ig_sig_key_version=4
← 200 	 31B
RESPONSE: {"configs": {}, "status": "ok"}

POST:  https://b.i.instagram.com/api/v1/attribution/log_attribution/
DATA: signed_body=0ea1d6f0be39353b3b33a883852fa1ad6b5603a8b3de207d12ffbbafc76b197f.{"adid":"d65ac716-b5d1-405d-8a83-813c96a126ee"}&ig_sig_key_version=4
← 200 	 16B
RESPONSE: {"status": "ok"}

GET:  https://b.i.instagram.com/api/v1/zr/token/result/?device_id=android-8d2a937cd8dda762&token_hash=6c0c2ce7759a6ded4952152b82dd4d5d&custom_device_id=cb40d085-9753-4af6-b830-eaf60acd4be9&fetch_reason=token_expired
→ 0B
← 200 	 744B
RESPONSE: {"token": {"carrier_name": "", "carrier_id": 1023, "ttl": 72000, "features": [],.........****omitted**"}

Something went wrong: Network: CURL error 6: Could not resolve host: i\\.instagram.com (see http://curl.haxx.se/libcurl/c/libcurl-errors.html).

Process finished with exit code 0

Something went wrong: Network: CURL error 6: Could not resolve host: i\\.instagram.com (see http://curl.haxx.se/libcurl/c/libcurl-errors.html).

Code is trying to make request to i\\.instagram.com. There is something weird with regex.  It is making 5 successfull api call but this api calls starts with b.i.instagram. The last one has "\" on uri

**Comment by valga** [comment] 2018-12-26 15:15
@ilkerbfl Please post omitted response from the last succeeded request.

**Comment by ilkerbfl** [comment] 2018-12-27 14:48
@valga  in history there is version which is not omitted if you need any other response
GET: https://b.i.instagram.com/api/v1/zr/token/result/?device_id=android-8d2a937cd8dda762&token_hash=6c0c2ce7759a6ded4952152b82dd4d5d&custom_device_id=cb40d085-9753-4af6-b830-eaf60acd4be9&fetch_reason=token_expired
→ 0B
← 200 744B
RESPONSE: {"token": {"carrier_name": "", "carrier_id": 1023, "ttl": 72000, "features": [], "request_time": 1545762408, "token_hash": "6c0c2ce7759a6ded4952152b82dd4d5d", "rewrite_rules": [{"matcher": "^(https?)://(i|z-p4\.i|z-p42\.i|b\.i)\.(([0-9a-zA-Z\.-])?instagram\.com(:?[0-9]{0,5}))(/api/v1/(?:accounts/read_msisdn_header|accounts/msisdn_header_bootstrap|zr/token/result))($|\?.$|/.$)", "replacer": "$1://b\.i\.$3$6$7"}, {"matcher": "^(https?)://(?:z-p4-|z-p42-)?(instagram\.)((?:fadb1-2|fadb1-1|fadb2-1|fesb1-1|fesb1-2|fist2-4|fuab1-2|fuab1-1|fist2-1|fist2-2|fist2-3|fist1-2|fist1-1)\.fna)(\.fbcdn\.net(:?[0-9]{0,5}))(/.(\.mp4|\.hls|\.flv)(\?.)?$)", "replacer": "$1://$2$3$4$6"}, {"matcher": "^(https?)://(?:z-p4-|z-p42-)?(instagram\.)((?:fadb1-2|fadb1-1|fadb2-1|fesb1-1|fesb1-2|fist2-4|fuab1-2|fuab1-1|fist2-1|fist2-2|fist2-3|fist1-2|fist1-1)\.fna)(\.fbcdn\.net(:?[0-9]{0,5}))($|\?.$|/.$)", "replacer": "$1://$2$3$4$6"}, {"matcher": "^(https?)://(?:z-p4-|z-p42-)?(instagram\.)(f\w+-\w+\.fna)(\.fbcdn\.net(:?[0-9]{0,5}))(/.(\.mp4|\.hls|\.flv)(\?.)?$)", "replacer": "$1://scontent\.cdninstagram\.com$6"}, {"matcher": "^(https?)://(?:z-p4-|z-p42-)?(instagram\.)(f\w+-\w+\.fna)(\.fbcdn\.net(:?[0-9]{0,5}))($|\?.$|/.$)", "replacer": "$1://scontent\.cdninstagram\.com$6"}, {"matcher": "^(https?)://(?:z-p4-|z-p42-|z-p15-)?([0-9a-zA-Z\.-]+)(?:-[0-9a-zA-Z]+-sonar)?(\.cdninstagram\.com(:?[0-9]{0,5}))(/.(\.mp4|\.hls|\.flv)(\?.)?$)", "replacer": "$1://$2$3$5"}, {"matcher": "^(https?)://(?:z-p4-|z-p42-|z-p15-)?([0-9a-zA-Z\.-]+)(?:-[0-9a-zA-Z]+-sonar)?(\.cdninstagram\.com(:?[0-9]{0,5}))($|\?.$|/.$)", "replacer": "$1://$2$3$5"}, {"matcher": "^(edge-mqtt|mqtt-ig-p4|mqtt-[0-9a-zA-Z]+)\.([0-9a-zA-Z\.-])?facebook\.com(:?[0-9]{0,5})", "replacer": "mqtt-ig-p4.$2facebook.com$3"}, {"matcher": "^(https?)://(i|z-p4\.i|z-p42\.i|b\.i)\.(([0-9a-zA-Z\.-])?instagram\.com(:?[0-9]{0,5}))((?:/rupload_igvideo|/api/v1/upload/video)(?:$|\?.$|/.$))", "replacer": "$1://i\.$3$6"}, {"matcher": "^(https?)://(i|z-p4\.i|z-p42\.i|b\.i)\.(([0-9a-zA-Z\.-])?instagram\.com(:?[0-9]{0,5}))($|\?.$|/.$)", "replacer": "$1://i\.$3$6"}, {"matcher": "^(https?)://(graph|z-p4\.graph|z-p42\.graph)\.(([0-9a-zA-Z\.-])?instagram\.com(:?[0-9]{0,5}))($|\?.$|/.$)", "replacer": "$1://graph\.$3$6"}, {"matcher": "^(https?)://(maps|z-p4\.maps|z-p42\.maps)\.(([0-9a-zA-Z\.-])?instagram\.com(:?[0-9]{0,5}))($|\?.$|/.$)", "replacer": "$1://maps\.$3$6"}, {"matcher": "^(https?)://(upload|z-p4\.upload|z-p42\.upload)\.(([0-9a-zA-Z\.-])?instagram\.com(:?[0-9]{0,5}))($|\?.$|/.*$)", "replacer": "$1://upload\.$3$6"}], "enabled_wallet_defs_keys": ["1023.instagram_special_pricing_template_1.all_special_pricing"], "deadline": "", "zero_cms_fetch_interval_seconds": 86400}, "status": "ok"}

**Comment by ilkerbfl** [comment] 2018-12-27 14:50
Actually i tried with docker also I have taken same error.

**Comment by cbo64** [comment] 2019-01-07 20:19
I've same issue. I've tested a replace action \\. by . in Curlfactory library : the error "CURL error 6: Could not resolve host: i\.instagram.com" was fixed. But i've an other error in a next step with a POST action with the same  i\.instagram.com called...

**Comment by mgp25** [comment] 2019-01-07 21:56
It would be great if any of you facing this issue, send me via email credentials to test with the account.

Regards

**Comment by cbo64** [comment] 2019-01-08 11:53
Thanks for your reply.

I've the same issue with all my accounts, so i give you a test account
(more secure for me) :

login : cbo642609
pwd : asd56jK

Two-factor app is enable. For your test, you can use a rescue code : 6825
9740

as i said on github issue, i've tested by doing a replace \\. by . in
CurlFactory, the issue is fixed. But then i've a POST trace with same URL
problem with i\.instragram.com. So the bug must be fixed in URL sended to
the curl library.

best regards.

He is the new trace with this test account :

POST: https://b.i.instagram.com/api/v1/accounts/read_msisdn_header/
DATA:
signed_body=42e9186ddc3236657e86145545813da1a5f019f42432d705d42dc4878913f4e5.{"mobile_subno_usage":"ig_select_app","device_id":"3af4a3c7-ee29-446b-92e6-84040fd467b7"}&ig_sig_key_version=4
← 200 16B
RESPONSE: {"status": "ok"}

POST: https://b.i.instagram.com/api/v1/qe/sync/
DATA:
signed_body=a5ca228a1f45dac1ab14339437b266e8f2e3de323e7afcd7fc2984e1ae4092e6.{"id":"3af4a3c7-ee29-446b-92e6-84040fd467b7","experiments":"ig_growth_android_profile_pic_prefill_with_fb_pic_2,ig_android_react_updater_universe,ig_android_autosubmit_password_recovery_universe,ig_android_background_voice_phone_confirmation_prefilled_phone_number_only,ig_android_pendingmediamanager_sessionscoped_universe,ig_android_report_nux_completed_device,ig_android_background_voice_confirmation_block_argentinian_numbers,ig_android_device_verification_fb_signup,ig_android_reg_nux_headers_cleanup_universe,ig_android_reg_omnibox,ig_android_background_voice_phone_confirmation,ig_android_gmail_autocomplete_account_over_one_tap,ig_android_skip_signup_from_one_tap_if_no_fb_sso,ig_android_access_flow_prefill,ig_android_session_scope_third_party,ig_android_email_suggestions_universe,ig_android_contact_import_placement_universe,ig_android_ask_for_permissions_on_reg,ig_android_only_prefill_free_email_address_in_reg,ig_android_notification_processing_universe,ig_android_run_device_verification,ig_android_onboarding_skip_fb_connect,ig_android_account_switch_infra_universe,ig_android_browser_service_job_intent_universe,ig_restore_focus_on_reg_textbox_universe,ig_android_do_not_skip_ci_in_fb_reg_flow,ig_android_session_scoping_facebook_account,ig_android_security_intent_switchoff,ig_android_do_not_show_back_button_in_nux_user_list,ig_android_invalid_onetap_universe,ig_client_logging_efficiency,ig_android_show_password_in_reg_universe,ig_android_aymh_signal_collecting_kill_switch,ig_android_nux_add_email_device,ig_android_multi_tap_login_new,ig_android_fci_onboarding_friend_search,ig_android_ui_cleanup_in_reg_v2,ig_android_editable_username_in_reg,ig_android_one_tap_show_logged_out_only_user,ig_android_phone_auto_login_during_reg,ig_android_one_tap_fallback_auto_login,ig_android_updated_copy_user_lookup_failed,ig_fb_invite_entry_points,ig_android_typeahead_subsequence_matching,ig_android_hsite_prefill_new_carrier,ig_android_gmail_oauth_in_reg,ig_two_fac_login_screen,ig_android_run_account_nux_on_server_cue_device,ig_android_gms_registration_universe,ig_android_bundle_size_audit_universe,ig_android_passwordless_auth,ig_android_sim_info_upload,ig_android_universe_noticiation_channels,ig_android_analytics_accessibility_event,ig_android_direct_main_tab_universe,ig_android_login_provider_migration,ig_android_email_one_tap_auto_login_during_reg,ig_android_prefill_full_name_from_fb,ig_android_local_2018_h2_holdout,ig_android_directapp_camera_open_and_reset_universe,ig_challenge_kill_switch,ig_android_video_bug_report_universe,ig_account_recovery_with_code_android_universe,ig_prioritize_user_input_on_switch_to_signup,ig_android_modularized_nux_universe_device,ig_android_account_recovery_auto_login,ig_android_onetaplogin_login_upsell,ig_android_hide_typeahead_for_logged_users,ig_android_targeted_one_tap_upsell_universe,ig_android_caption_typeahead_fix_on_o_universe,ig_android_retry_create_account_universe,ig_android_crosshare_feed_post,ig_android_abandoned_reg_flow,ig_android_remember_password_at_login,ig_android_smartlock_hints_universe,ig_android_2fac_auto_fill_sms_universe,ig_type_ahead_recover_account,ig_android_onetaplogin_optimization,ig_android_family_apps_user_values_provider_universe,ig_android_direct_inbox_account_switching,ig_android_exoplayer_settings,ig_sem_resurrection_logging,ig_android_login_forgot_password_universe,ig_android_hide_fb_flow_in_add_account_flow,ig_android_dialog_email_reg_error_universe,ig_android_low_priority_notifications_universe,ig_android_device_sms_retriever_plugin_universe,ig_android_show_explore_people_as_last_step_in_nux,ig_android_device_verification_separate_endpoint,ig_android_restore_focus_on_textbox_reg_universe"}&ig_sig_key_version=4
← 200 1.54kB
RESPONSE: {"experiments": [{"name":
"ig_android_background_voice_phone_confirmation_prefilled_phone_number_only",
"group": "test", "additional_params": [], "params": [{"name": "enabled",
"value": "true"}], "expired": true}, {"name":
"ig_android_background_voice_confirmation_block_argentinian_numbers",
"group": "test", "additional_params": [], "params": [{"name": "enabled",
"value": "true"}], "expired": true}, {"name":
"ig_android_reg_nux_headers_cleanup_universe", "group": "test_label",
"additional_params": [], "params": [{"name": "password_mask_toggle",
"value": "label"}], "logging_id": "306441029966076", "expired": false},
{"name": "ig_android_skip_signup_from_one_tap_if_no_fb_sso", "group":
"control_0724", "additional_params": [], "params": [{"name":
"skip_allowed", "value": "false"}], "expired": true}, {"name":
"ig_android_access_flow_prefill", "group": "launch", "additional_params":
[], "params": [{"name": "long_timeout", "value": "true"}, {"name":
"is_enabled", "value": "true"}], "expired": true}, {"name":
"ig_android_session_scope_third_party", "group": "control",
"additional_params": [], "params": [{"name": "enabled", "value": "false"}],
"expired": true}, {"name":
"ig_android_only_prefill_free_email_address_in_reg", "group":
"test_prefill_empty", "additional_params": [], "params": [{"name":
"enabled", "value": "true"}, {"name": "prefill_empty", "value": "true"}],
"expired": true}, {"name": "ig_android_notification_processing_universe",
"group": "test", "additional_params": [], "params": [{"name":
"in_fbns_receiver", "value": "true"}, {"name": "in_receiver", "value":
"true"}], "expired": true}, {"name": "ig_android_run_device_verification",
"group": "test_both", "additional_params": [], "params": [{"name":
"run_device_verification", "value": "verification_run_check"}], "expired":
true}, {"name": "ig_android_browser_service_job_intent_universe", "group":
"test", "additional_params": [], "params": [{"name": "is_enabled", "value":
"true"}], "expired": true}, {"name":
"ig_android_do_not_skip_ci_in_fb_reg_flow", "group": "test",
"additional_params": [], "params": [{"name": "enabled", "value": "true"}],
"expired": true}, {"name": "ig_android_session_scoping_facebook_account",
"group": "control", "additional_params": [], "params": [{"name":
"kill_switch_wipe_out", "value": "false"}, {"name": "enabled", "value":
"false"}], "logging_id": "245704142690072", "expired": false}, {"name":
"ig_android_security_intent_switchoff", "group": "allusers",
"additional_params": [], "params": [{"name": "switch_offs", "value": ""}],
"logging_id": "185334452042071", "expired": false}, {"name":
"ig_android_do_not_show_back_button_in_nux_user_list", "group": "test",
"additional_params": [], "params": [{"name": "enabled", "value": "true"}],
"expired": true}, {"name": "ig_android_invalid_onetap_universe", "group":
"control", "additional_params": [], "params": [{"name": "show_dialog",
"value": "false"}], "expired": true}, {"name":
"ig_android_nux_add_email_device", "group": "auto_conf",
"additional_params": [], "params": [{"name": "try_auto_conf", "value":
"true"}, {"name": "enabled", "value": "true"}, {"name":
"prefetch_email_without_oauth", "value": "false"}, {"name":
"prefetch_email_location", "value": "nux_start"}], "logging_id":
"2162383917342522", "expired": false}, {"name":
"ig_android_multi_tap_login_new", "group": "test", "additional_params": [],
"params": [{"name": "enabled", "value": "true"}, {"name":
"show_logged_out_only", "value": "true"}], "logging_id": "307876533367963",
"expired": false}, {"name": "ig_android_ui_cleanup_in_reg_v2", "group":
"test_with_tertiary_ci_opt_out_with_tertiary_style_test_0213",
"additional_params": [], "params": [{"name":
"secondary_text_link_style_fix_expose", "value": "true"}, {"name":
"next_button_disable_style", "value": "filled_blue_when_disabled"},
{"name": "secondary_text_link_style_fix", "value":
"test_with_tertiary_ci_opt_out"}, {"name": "tertiary_text_link_style_fix",
"value": "test"}], "expired": true}, {"name":
"ig_android_typeahead_subsequence_matching", "group": "launch",
"additional_params": [], "params": [{"name": "is_enabled", "value":
"true"}], "expired": true}, {"name":
"ig_android_hsite_prefill_new_carrier", "group": "control_0108",
"additional_params": [], "params": [{"name": "prefill_enabled", "value":
"true"}], "expired": true}, {"name": "ig_android_gmail_oauth_in_reg",
"group": "rollout_1201", "additional_params": [], "params": [{"name":
"try_background_confirm", "value": "true"}], "expired": true}, {"name":
"ig_android_run_account_nux_on_server_cue_device", "group": "test_1016_v2",
"additional_params": [], "params": [{"name": "show_account_nux", "value":
"true"}], "expired": true}, {"name":
"ig_android_gms_registration_universe", "group": "test",
"additional_params": [], "params": [{"name": "is_enabled", "value":
"true"}], "expired": true}, {"name": "ig_android_passwordless_auth",
"group": "control_0920", "additional_params": [], "params": [{"name":
"allow_vetted_login_from_phone", "value": "false"}, {"name":
"weeks_vetted", "value": "3"}], "expired": true}, {"name":
"ig_android_sim_info_upload", "group": "test", "additional_params": [],
"params": [{"name": "enable_upload", "value": "true"}], "expired": true},
{"name": "ig_android_analytics_accessibility_event", "group": "test",
"additional_params": [], "params": [{"name": "is_enabled", "value":
"false"}], "expired": true}, {"name":
"ig_android_login_provider_migration", "group": "rollout",
"additional_params": [], "params": [{"name": "enable_login_provider",
"value": "true"}], "expired": true}, {"name":
"ig_android_email_one_tap_auto_login_during_reg", "group": "test_1205",
"additional_params": [], "params": [{"name": "is_participating", "value":
"true"}, {"name": "show_dialog", "value": "true"}], "expired": true},
{"name": "ig_challenge_kill_switch", "group": "test", "additional_params":
[], "params": [{"name": "is_enabled", "value": "true"}], "expired": true},
{"name": "ig_account_recovery_with_code_android_universe", "group":
"control", "additional_params": [], "params": [{"name": "enabled", "value":
"false"}, {"name": "ask_for_sms_permission", "value": "false"}, {"name":
"weeks_vetted", "value": "3"}], "expired": true}, {"name":
"ig_android_modularized_nux_universe_device", "group":
"roll_out_dynamic_onboarding_0612", "additional_params": [], "params":
[{"name": "request_from_server", "value": "true"}, {"name":
"increment_following_count", "value": "true"}, {"name": "run_from_plugin",
"value": "true"}], "expired": true}, {"name":
"ig_android_onetaplogin_login_upsell", "group":
"cap_1_logout_not_affected_0814", "additional_params": [], "params":
[{"name": "should_affect_logout_upsell", "value": "false"}, {"name":
"upsell_cap", "value": "1"}], "expired": true}, {"name":
"ig_android_targeted_one_tap_upsell_universe", "group": "test",
"additional_params": [], "params": [{"name": "show_upsell", "value":
"true"}, {"name": "dialog", "value": "1"}, {"name":
"invalid_password_attempt_limit", "value": "1"}], "expired": true},
{"name": "ig_android_family_apps_user_values_provider_universe", "group":
"test", "additional_params": [], "params": [{"name":
"should_provide_user_values", "value": "true"}], "expired": true}, {"name":
"ig_android_direct_inbox_account_switching", "group": "test",
"additional_params": [], "params": [{"name": "should_show_badging",
"value": "false"}, {"name": "is_enabled", "value": "true"}], "expired":
true}, {"name": "ig_android_hide_fb_flow_in_add_account_flow", "group":
"control_0609", "additional_params": [], "params": [{"name":
"hide_for_unknown_fbid", "value": "true"}, {"name": "is_enabled", "value":
"true"}], "expired": true}, {"name":
"ig_android_low_priority_notifications_universe", "group": "test",
"additional_params": [], "params": [{"name": "as_job", "value": "true"}],
"expired": true}, {"name":
"ig_android_device_sms_retriever_plugin_universe", "group": "test",
"additional_params": [], "params": [{"name": "shrink_message", "value":
"false"}], "expired": true}, {"name":
"ig_android_restore_focus_on_textbox_reg_universe", "group": "test",
"additional_params": [], "params": [{"name": "is_enabled", "value":
"true"}], "logging_id": "301916817074405", "expired": false}], "status":
"ok"}

POST: https://b.i.instagram.com/api/v1/launcher/sync/
DATA:
signed_body=8fd1b8ad4724fbb21379503e2a309c7a05881f8069075bdd389dcddf3a83464d.{"_csrftoken":"xglUIYm3sPROD2OmMrDXINa9kV4xs5PW","id":"3af4a3c7-ee29-446b-92e6-84040fd467b7","configs":""}&ig_sig_key_version=4
← 200 31B
RESPONSE: {"configs": {}, "status": "ok"}

POST: https://b.i.instagram.com/api/v1/attribution/log_attribution/
DATA:
signed_body=97c96e06b6013c67338304c3ce23034c9f56160240d27ad2563fa598ec084af2.{"adid":"dc6d8414-5f6b-4a69-8471-55a4b2dfaf94"}&ig_sig_key_version=4
← 200 16B
RESPONSE: {"status": "ok"}

GET:
https://b.i.instagram.com/api/v1/zr/token/result/?device_id=android-fa32eddb1d02dc3c&token_hash=6c0c2ce7759a6ded4952152b82dd4d5d&custom_device_id=3af4a3c7-ee29-446b-92e6-84040fd467b7&fetch_reason=token_expired
→ 0B
← 200 736B
RESPONSE: {"token": {"carrier_name": "", "carrier_id": 1005, "ttl": 72000,
"features": [], "request_time": 1546948169, "token_hash":
"6c0c2ce7759a6ded4952152b82dd4d5d", "rewrite_rules": [{"matcher":
"^(https?)://(i|z-p4\\.i|z-p42\\.i|b\\.i)\\.(([0-9a-zA-Z\\.-]*)?instagram\\.com(:?[0-9]{0,5}))(/api/v1/(?:accounts/read_msisdn_header|accounts/msisdn_header_bootstrap|zr/token/result))($|\\?.*$|/.*$)",
"replacer": "$1://b\\.i\\.$3$6$7"}, {"matcher":
"^(https?)://(?:z-p4-|z-p42-)?(instagram\\.)((?:fakl5-1|fham2-1|fmuc4-1|fchc2-1|fwlg2-1|fakl6-1|ftxl2-1|fakl4-1)\\.fna)(\\.fbcdn\\.net(:?[0-9]{0,5}))(/.*(\\.mp4|\\.hls|\\.flv)(\\?.*)?$)",
"replacer": "$1://$2$3$4$6"}, {"matcher":
"^(https?)://(?:z-p4-|z-p42-)?(instagram\\.)((?:fakl5-1|fham2-1|fmuc4-1|fchc2-1|fwlg2-1|fakl6-1|ftxl2-1|fakl4-1)\\.fna)(\\.fbcdn\\.net(:?[0-9]{0,5}))($|\\?.*$|/.*$)",
"replacer": "$1://$2$3$4$6"}, {"matcher":
"^(https?)://(?:z-p4-|z-p42-)?(instagram\\.)(f\\w+-\\w+\\.fna)(\\.fbcdn\\.net(:?[0-9]{0,5}))(/.*(\\.mp4|\\.hls|\\.flv)(\\?.*)?$)",
"replacer": "$1://scontent\\.cdninstagram\\.com$6"}, {"matcher":
"^(https?)://(?:z-p4-|z-p42-)?(instagram\\.)(f\\w+-\\w+\\.fna)(\\.fbcdn\\.net(:?[0-9]{0,5}))($|\\?.*$|/.*$)",
"replacer": "$1://scontent\\.cdninstagram\\.com$6"}, {"matcher":
"^(https?)://(?:z-p4-|z-p42-|z-p15-)?([0-9a-zA-Z\\.-]+)(?:-[0-9a-zA-Z]+-sonar)?(\\.cdninstagram\\.com(:?[0-9]{0,5}))(/.*(\\.mp4|\\.hls|\\.flv)(\\?.*)?$)",
"replacer": "$1://$2$3$5"}, {"matcher":
"^(https?)://(?:z-p4-|z-p42-|z-p15-)?([0-9a-zA-Z\\.-]+)(?:-[0-9a-zA-Z]+-sonar)?(\\.cdninstagram\\.com(:?[0-9]{0,5}))($|\\?.*$|/.*$)",
"replacer": "$1://$2$3$5"}, {"matcher":
"^(edge-mqtt|mqtt-ig-p4|mqtt-[0-9a-zA-Z]+)\\.([0-9a-zA-Z\\.-]*)?facebook\\.com(:?[0-9]{0,5})",
"replacer": "mqtt-ig-p4.$2facebook.com$3"}, {"matcher":
"^(https?)://(i|z-p4\\.i|z-p42\\.i|b\\.i)\\.(([0-9a-zA-Z\\.-]*)?instagram\\.com(:?[0-9]{0,5}))((?:/rupload_igvideo|/api/v1/upload/video)(?:$|\\?.*$|/.*$))",
"replacer": "$1://i\\.$3$6"}, {"matcher":
"^(https?)://(i|z-p4\\.i|z-p42\\.i|b\\.i)\\.(([0-9a-zA-Z\\.-]*)?instagram\\.com(:?[0-9]{0,5}))($|\\?.*$|/.*$)",
"replacer": "$1://i\\.$3$6"}, {"matcher":
"^(https?)://(graph|z-p4\\.graph|z-p42\\.graph)\\.(([0-9a-zA-Z\\.-]*)?instagram\\.com(:?[0-9]{0,5}))($|\\?.*$|/.*$)",
"replacer": "$1://graph\\.$3$6"}, {"matcher":
"^(https?)://(maps|z-p4\\.maps|z-p42\\.maps)\\.(([0-9a-zA-Z\\.-]*)?instagram\\.com(:?[0-9]{0,5}))($|\\?.*$|/.*$)",
"replacer": "$1://maps\\.$3$6"}, {"matcher":
"^(https?)://(upload|z-p4\\.upload|z-p42\\.upload)\\.(([0-9a-zA-Z\\.-]*)?instagram\\.com(:?[0-9]{0,5}))($|\\?.*$|/.*$)",
"replacer": "$1://upload\\.$3$6"}], "enabled_wallet_defs_keys":
["1005.instagram_special_pricing_template_1.all_special_pricing"],
"deadline": "", "zero_cms_fetch_interval_seconds": 86400}, "status": "ok"}

Something went wrong: Network: CURL error 6: Could not resolve host: i\.
instagram.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html).

**Comment by dabe93** [comment] 2019-01-09 19:06
i have the same issue when trying to login.
I used the API until this morning then in the afternoon stopped working.
The strange thing is that with one single account is still working, but with any other account, also with other used until today without problems, it returns this error.

Please I have to use it tomorrow so it's important to me to bring it back as soon as possible.

Thank you very much.

**Comment by dabe93** [comment] 2019-01-09 20:46
I've tried with more accounts. With some I get the error, with other no..

**Comment by valga** [comment] 2019-02-09 09:23
@mgp25 I see escaped dots in matchers. Does Java really require escaped dots in replacements?

**Comment by mgp25** [comment] 2019-02-09 09:26
@valga checking…

**Comment by dabe93** [comment] 2019-02-09 09:27
Hi all, i've discovered that in my case, as I first thought,  the issue was caused by the network. The problem is that the request is cached or similar in the API, so even if you resolve the network error you will always have the issue. Trying to completely re-install the API and all the dependencies solved, but probably is enough to delete session data.

If the problem is not network related I don't have a solution for that.

Related to that "cache problem" I noticed that if you succeed to login once, the the API use always the password used first, not the one you enter. So if you insert the wrong password on purpose you will still get able to login. You have to delete the session data to get the login fail. Is that behavior normal?

**Comment by mgp25** [comment] 2019-02-09 09:30
@valga it seems so!

**Closed** 2019-02-09 09:58 UTC

**Comment by valga** [comment] 2019-02-09 10:02
@dabe93 Instagram has an agreement with some ISP to make data usage free of charge for its users. To make this happen they must normalize domain names. They do it with regular expressions, but Java and PHP have different regex engines, so sometimes our code may fail.

**Comment by dabe93** [comment] 2019-02-09 10:06
@valga in fact for me happened with a mobile connection. With "cable" connection never happened.

**Comment by thalisvilela** [comment] 2019-03-01 14:37
> @dabe93 Instagram has an agreement with some ISPs to make data usage free of charge for its users. To make this happen they must normalize domain names. They do it with regular expressions, but Java and PHP have different regex engines, so sometimes our code may fail.

You sir, saved my day! Changed my gateway to another ISP, problem solved!

**Comment by BrokedTV** [comment] 2019-03-03 20:07
> > @dabe93 Instagram has an agreement with some ISPs to make data usage free of charge for its users. To make this happen they must normalize domain names. They do it with regular expressions, but Java and PHP have different regex engines, so sometimes our code may fail.
> 
> You sir, saved my day! Changed my gateway to another ISP, problem solved!

hey @thalisvilela , can you explain more in details on how you fix this error? where do you change the gateway, i have been trying to fix this error for the last 10 days.
Appreciated
