### ISSUE TITLE
Failed uploading video

### ISSUE THREAD

**Issue by akhur02** [mgp25/Instagram-API#2559] opened 2019-03-12 09:23 UTC
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---
On uploading album with video I got error - Upload of "86194bc69bc472a87d4756b0d610c810.mp4" failed: There are no more upload URLs

Trying like this example https://github.com/mgp25/Instagram-API/blob/master/examples/uploadAlbum.php  
---

```

Error Log/var_dump:

```php

RESPONSE: {"status": "fail", "message": "Upload of "86194bc69bc472a87d4756b0d610c810.mp4" failed: There are no more upload URLs."}

```

---

### For a new endpoint *feature request*, you should include the *capture of the request and response*.

Request:

```http
# Please provide your capture below, for example:

GET /api/v1/si/fetch_headers/?guid=123456abcdeff19cc2f123456&challenge_type=signup HTTP/1.1
Host: i.instagram.com
Connection: keep-alive
X-IG-Connection-Type: mobile(UMTS)
X-IG-Capabilities: 3ToAAA==
Accept-Language: en-US
Cookie: csrftoken=g79dofABCDEFGII3LI7YdHei1234567; mid=WFI52QABAAGrbKL-ABCDEFGHIJK
User-Agent: Instagram 10.3.0 Android (18/4.3; 320dpi; 720x1280; Xiaomi; HM 1SW; armani; qcom; en_US)
Accept-Encoding: gzip, deflate, sdch
```

**Comment by JRoy** [comment] 2019-03-13 21:28
Duplicate of #2564

**Closed by JRoy** 2019-03-13 21:28 UTC
