### ISSUE TITLE
Story Test (question) sticker

### ISSUE THREAD

**Issue by denemeyapiyorum** [mgp25/Instagram-API#2675] opened 2019-05-26 08:08 UTC
Hello dear mgp25,

It's best tool ever, I didnt see "test sticker" in this project eveni check your example files.

What's test sticker?

> **"Where are you from?"**
> A) XXXX
> B) YYYY
> C) ZZZZ
> D) AAAA

Maybe you calling with different name, what's global name i am not sure...Can you add this api to project?

Thank you for answer.

**Comment by mgp25** [comment] 2019-05-26 08:37
Hello,

You should follow issue template, otherwise this will considered as invalid. Please try to follow repository rules.

When opening this kind of issue (`Feature request`) provide as much as information as possible, including links to pages that explain that concrete feature. Believe or not, I am not an Instagram user, it is always appreciate to have extra information not just for us but for anyone trying to follow up the issue.

Best regards.

**Comment by JRoy** [comment] 2019-05-26 14:36
Duplicate of #2642

**Closed by JRoy** 2019-05-26 14:36 UTC
